/*
 * SysML v2 API and Services
 *
 * REST/HTTP binding (PSM) for the SysML v2 standard API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Xunit;
using Microsoft.Extensions.DependencyInjection;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;


/* *********************************************************************************
*              Follow these manual steps to construct tests.
*              This file will not be overwritten.
*  *********************************************************************************
* 1. Navigate to ApiTests.Base.cs and ensure any tokens are being created correctly.
*    Take care not to commit credentials to any repository.
*
* 2. Mocking is coordinated by ApiTestsBase#AddApiHttpClients.
*    To mock the client, use the generic AddApiHttpClients.
*    To mock the server, change the client's BaseAddress.
*
* 3. Locate the test you want below
*      - remove the skip property from the Fact attribute
*      - set the value of any variables if necessary
*
* 4. Run the tests and ensure they work.
*
*/


namespace Org.OpenAPITools.Test.Api
{
    /// <summary>
    ///  Class for testing BranchApi
    /// </summary>
    public sealed class BranchApiTests : ApiTestsBase
    {
        private readonly IBranchApi _instance;

        public BranchApiTests(): base(Array.Empty<string>())
        {
            _instance = _host.Services.GetRequiredService<IBranchApi>();
        }

        /// <summary>
        /// Test DeleteBranchByProjectAndId
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task DeleteBranchByProjectAndIdAsyncTest()
        {
            Guid projectId = default!;
            Guid branchId = default!;
            var response = await _instance.DeleteBranchByProjectAndIdAsync(projectId, branchId);
            var model = response.Ok();
            Assert.IsType<Branch>(model);
        }

        /// <summary>
        /// Test GetBranchesByProject
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task GetBranchesByProjectAsyncTest()
        {
            Guid projectId = default!;
            Client.Option<string> pageAfter = default!;
            Client.Option<string> pageBefore = default!;
            Client.Option<int> pageSize = default!;
            var response = await _instance.GetBranchesByProjectAsync(projectId, pageAfter, pageBefore, pageSize);
            var model = response.Ok();
            Assert.IsType<List<Branch>>(model);
        }

        /// <summary>
        /// Test GetBranchesByProjectAndId
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task GetBranchesByProjectAndIdAsyncTest()
        {
            Guid projectId = default!;
            Guid branchId = default!;
            var response = await _instance.GetBranchesByProjectAndIdAsync(projectId, branchId);
            var model = response.Ok();
            Assert.IsType<Branch>(model);
        }

        /// <summary>
        /// Test PostBranchByProject
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task PostBranchByProjectAsyncTest()
        {
            Guid projectId = default!;
            Branch body = default!;
            var response = await _instance.PostBranchByProjectAsync(projectId, body);
            var model = response.Created();
            Assert.IsType<Branch>(model);
        }
    }
}
