/*
 * SysML v2 API and Services
 *
 * REST/HTTP binding (PSM) for the SysML v2 standard API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Xunit;
using Microsoft.Extensions.DependencyInjection;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;


/* *********************************************************************************
*              Follow these manual steps to construct tests.
*              This file will not be overwritten.
*  *********************************************************************************
* 1. Navigate to ApiTests.Base.cs and ensure any tokens are being created correctly.
*    Take care not to commit credentials to any repository.
*
* 2. Mocking is coordinated by ApiTestsBase#AddApiHttpClients.
*    To mock the client, use the generic AddApiHttpClients.
*    To mock the server, change the client's BaseAddress.
*
* 3. Locate the test you want below
*      - remove the skip property from the Fact attribute
*      - set the value of any variables if necessary
*
* 4. Run the tests and ensure they work.
*
*/


namespace Org.OpenAPITools.Test.Api
{
    /// <summary>
    ///  Class for testing ElementApi
    /// </summary>
    public sealed class ElementApiTests : ApiTestsBase
    {
        private readonly IElementApi _instance;

        public ElementApiTests(): base(Array.Empty<string>())
        {
            _instance = _host.Services.GetRequiredService<IElementApi>();
        }

        /// <summary>
        /// Test GetElementByProjectCommitId
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task GetElementByProjectCommitIdAsyncTest()
        {
            Guid projectId = default!;
            Guid commitId = default!;
            Guid elementId = default!;
            var response = await _instance.GetElementByProjectCommitIdAsync(projectId, commitId, elementId);
            var model = response.Ok();
            Assert.IsType<Element>(model);
        }

        /// <summary>
        /// Test GetElementsByProjectCommit
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task GetElementsByProjectCommitAsyncTest()
        {
            Guid projectId = default!;
            Guid commitId = default!;
            Client.Option<string> pageAfter = default!;
            Client.Option<string> pageBefore = default!;
            Client.Option<int> pageSize = default!;
            var response = await _instance.GetElementsByProjectCommitAsync(projectId, commitId, pageAfter, pageBefore, pageSize);
            var model = response.Ok();
            Assert.IsType<List<Element>>(model);
        }

        /// <summary>
        /// Test GetRootsByProjectCommit
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task GetRootsByProjectCommitAsyncTest()
        {
            Guid projectId = default!;
            Guid commitId = default!;
            Client.Option<string> pageAfter = default!;
            Client.Option<string> pageBefore = default!;
            Client.Option<int> pageSize = default!;
            var response = await _instance.GetRootsByProjectCommitAsync(projectId, commitId, pageAfter, pageBefore, pageSize);
            var model = response.Ok();
            Assert.IsType<List<Element>>(model);
        }
    }
}
