/*
 * SysML v2 API and Services
 *
 * REST/HTTP binding (PSM) for the SysML v2 standard API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Xunit;
using Microsoft.Extensions.DependencyInjection;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;


/* *********************************************************************************
*              Follow these manual steps to construct tests.
*              This file will not be overwritten.
*  *********************************************************************************
* 1. Navigate to ApiTests.Base.cs and ensure any tokens are being created correctly.
*    Take care not to commit credentials to any repository.
*
* 2. Mocking is coordinated by ApiTestsBase#AddApiHttpClients.
*    To mock the client, use the generic AddApiHttpClients.
*    To mock the server, change the client's BaseAddress.
*
* 3. Locate the test you want below
*      - remove the skip property from the Fact attribute
*      - set the value of any variables if necessary
*
* 4. Run the tests and ensure they work.
*
*/


namespace Org.OpenAPITools.Test.Api
{
    /// <summary>
    ///  Class for testing QueryApi
    /// </summary>
    public sealed class QueryApiTests : ApiTestsBase
    {
        private readonly IQueryApi _instance;

        public QueryApiTests(): base(Array.Empty<string>())
        {
            _instance = _host.Services.GetRequiredService<IQueryApi>();
        }

        /// <summary>
        /// Test DeleteQueryByProjectAndId
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task DeleteQueryByProjectAndIdAsyncTest()
        {
            Guid projectId = default!;
            Guid queryId = default!;
            var response = await _instance.DeleteQueryByProjectAndIdAsync(projectId, queryId);
            var model = response.Ok();
            Assert.IsType<Query>(model);
        }

        /// <summary>
        /// Test GetQueriesByProject
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task GetQueriesByProjectAsyncTest()
        {
            Guid projectId = default!;
            Client.Option<string> pageAfter = default!;
            Client.Option<string> pageBefore = default!;
            Client.Option<int> pageSize = default!;
            var response = await _instance.GetQueriesByProjectAsync(projectId, pageAfter, pageBefore, pageSize);
            var model = response.Ok();
            Assert.IsType<List<Query>>(model);
        }

        /// <summary>
        /// Test GetQueryByProjectAndId
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task GetQueryByProjectAndIdAsyncTest()
        {
            Guid projectId = default!;
            Guid queryId = default!;
            var response = await _instance.GetQueryByProjectAndIdAsync(projectId, queryId);
            var model = response.Ok();
            Assert.IsType<Query>(model);
        }

        /// <summary>
        /// Test GetQueryResultsByProjectIdQuery
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task GetQueryResultsByProjectIdQueryAsyncTest()
        {
            Guid projectId = default!;
            Query body = default!;
            Client.Option<Guid> commitId = default!;
            var response = await _instance.GetQueryResultsByProjectIdQueryAsync(projectId, body, commitId);
            var model = response.Ok();
            Assert.IsType<List<Element>>(model);
        }

        /// <summary>
        /// Test GetQueryResultsByProjectIdQueryId
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task GetQueryResultsByProjectIdQueryIdAsyncTest()
        {
            Guid projectId = default!;
            Guid queryId = default!;
            Client.Option<Guid> commitId = default!;
            var response = await _instance.GetQueryResultsByProjectIdQueryIdAsync(projectId, queryId, commitId);
            var model = response.Ok();
            Assert.IsType<List<Element>>(model);
        }

        /// <summary>
        /// Test GetQueryResultsByProjectIdQueryPost
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task GetQueryResultsByProjectIdQueryPostAsyncTest()
        {
            Guid projectId = default!;
            Query body = default!;
            Client.Option<Guid> commitId = default!;
            var response = await _instance.GetQueryResultsByProjectIdQueryPostAsync(projectId, body, commitId);
            var model = response.Ok();
            Assert.IsType<List<Element>>(model);
        }

        /// <summary>
        /// Test PostQueryByProject
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task PostQueryByProjectAsyncTest()
        {
            Guid projectId = default!;
            Query body = default!;
            var response = await _instance.PostQueryByProjectAsync(projectId, body);
            var model = response.Created();
            Assert.IsType<Query>(model);
        }
    }
}
