// <auto-generated>
/*
 * SysML v2 API and Services
 *
 * REST/HTTP binding (PSM) for the SysML v2 standard API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections.Generic;
using System.Net;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text.Json;
using Org.OpenAPITools.Client;
using Org.OpenAPITools.Model;
using System.Diagnostics.CodeAnalysis;

namespace Org.OpenAPITools.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// This class is registered as transient.
    /// </summary>
    public interface IBranchApi : IApi
    {
        /// <summary>
        /// The class containing the events
        /// </summary>
        BranchApiEvents Events { get; }

        /// <summary>
        /// Delete branch by project and ID
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">ID of the project</param>
        /// <param name="branchId">ID of the branch</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IDeleteBranchByProjectAndIdApiResponse"/>&gt;</returns>
        Task<IDeleteBranchByProjectAndIdApiResponse> DeleteBranchByProjectAndIdAsync(Guid projectId, Guid branchId, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Delete branch by project and ID
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <param name="projectId">ID of the project</param>
        /// <param name="branchId">ID of the branch</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IDeleteBranchByProjectAndIdApiResponse"/>?&gt;</returns>
        Task<IDeleteBranchByProjectAndIdApiResponse?> DeleteBranchByProjectAndIdOrDefaultAsync(Guid projectId, Guid branchId, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Get branches by project
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">ID of the project</param>
        /// <param name="pageAfter">Page after (optional)</param>
        /// <param name="pageBefore">Page before (optional)</param>
        /// <param name="pageSize">Page size (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IGetBranchesByProjectApiResponse"/>&gt;</returns>
        Task<IGetBranchesByProjectApiResponse> GetBranchesByProjectAsync(Guid projectId, Option<string> pageAfter = default, Option<string> pageBefore = default, Option<int> pageSize = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Get branches by project
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <param name="projectId">ID of the project</param>
        /// <param name="pageAfter">Page after (optional)</param>
        /// <param name="pageBefore">Page before (optional)</param>
        /// <param name="pageSize">Page size (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IGetBranchesByProjectApiResponse"/>?&gt;</returns>
        Task<IGetBranchesByProjectApiResponse?> GetBranchesByProjectOrDefaultAsync(Guid projectId, Option<string> pageAfter = default, Option<string> pageBefore = default, Option<int> pageSize = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Get branch by project and ID
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">ID of the project</param>
        /// <param name="branchId">ID of the branch</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IGetBranchesByProjectAndIdApiResponse"/>&gt;</returns>
        Task<IGetBranchesByProjectAndIdApiResponse> GetBranchesByProjectAndIdAsync(Guid projectId, Guid branchId, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Get branch by project and ID
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <param name="projectId">ID of the project</param>
        /// <param name="branchId">ID of the branch</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IGetBranchesByProjectAndIdApiResponse"/>?&gt;</returns>
        Task<IGetBranchesByProjectAndIdApiResponse?> GetBranchesByProjectAndIdOrDefaultAsync(Guid projectId, Guid branchId, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Create branch by project
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">ID of the project</param>
        /// <param name="body"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IPostBranchByProjectApiResponse"/>&gt;</returns>
        Task<IPostBranchByProjectApiResponse> PostBranchByProjectAsync(Guid projectId, Branch body, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Create branch by project
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <param name="projectId">ID of the project</param>
        /// <param name="body"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IPostBranchByProjectApiResponse"/>?&gt;</returns>
        Task<IPostBranchByProjectApiResponse?> PostBranchByProjectOrDefaultAsync(Guid projectId, Branch body, System.Threading.CancellationToken cancellationToken = default);
    }

    /// <summary>
    /// The <see cref="IDeleteBranchByProjectAndIdApiResponse"/>
    /// </summary>
    public interface IDeleteBranchByProjectAndIdApiResponse : Org.OpenAPITools.Client.IApiResponse, IOk<Org.OpenAPITools.Model.Branch?>, IUnsupportedMediaType<Org.OpenAPITools.Model.Error?>, IInternalServerError<Org.OpenAPITools.Model.Error?>
    {
        /// <summary>
        /// Returns true if the response is 200 Ok
        /// </summary>
        /// <returns></returns>
        bool IsOk { get; }

        /// <summary>
        /// Returns true if the response is 404 NotFound
        /// </summary>
        /// <returns></returns>
        bool IsNotFound { get; }

        /// <summary>
        /// Returns true if the response is 415 UnsupportedMediaType
        /// </summary>
        /// <returns></returns>
        bool IsUnsupportedMediaType { get; }

        /// <summary>
        /// Returns true if the response is 500 InternalServerError
        /// </summary>
        /// <returns></returns>
        bool IsInternalServerError { get; }

        /// <summary>
        /// Returns true if the response is the default response type
        /// </summary>
        /// <returns></returns>
        bool IsDefault { get; }
    }

    /// <summary>
    /// The <see cref="IGetBranchesByProjectApiResponse"/>
    /// </summary>
    public interface IGetBranchesByProjectApiResponse : Org.OpenAPITools.Client.IApiResponse, IOk<List<Branch>?>, IUnsupportedMediaType<Org.OpenAPITools.Model.Error?>, IInternalServerError<Org.OpenAPITools.Model.Error?>
    {
        /// <summary>
        /// Returns true if the response is 200 Ok
        /// </summary>
        /// <returns></returns>
        bool IsOk { get; }

        /// <summary>
        /// Returns true if the response is 404 NotFound
        /// </summary>
        /// <returns></returns>
        bool IsNotFound { get; }

        /// <summary>
        /// Returns true if the response is 415 UnsupportedMediaType
        /// </summary>
        /// <returns></returns>
        bool IsUnsupportedMediaType { get; }

        /// <summary>
        /// Returns true if the response is 500 InternalServerError
        /// </summary>
        /// <returns></returns>
        bool IsInternalServerError { get; }

        /// <summary>
        /// Returns true if the response is the default response type
        /// </summary>
        /// <returns></returns>
        bool IsDefault { get; }
    }

    /// <summary>
    /// The <see cref="IGetBranchesByProjectAndIdApiResponse"/>
    /// </summary>
    public interface IGetBranchesByProjectAndIdApiResponse : Org.OpenAPITools.Client.IApiResponse, IOk<Org.OpenAPITools.Model.Branch?>, IUnsupportedMediaType<Org.OpenAPITools.Model.Error?>, IInternalServerError<Org.OpenAPITools.Model.Error?>
    {
        /// <summary>
        /// Returns true if the response is 200 Ok
        /// </summary>
        /// <returns></returns>
        bool IsOk { get; }

        /// <summary>
        /// Returns true if the response is 404 NotFound
        /// </summary>
        /// <returns></returns>
        bool IsNotFound { get; }

        /// <summary>
        /// Returns true if the response is 415 UnsupportedMediaType
        /// </summary>
        /// <returns></returns>
        bool IsUnsupportedMediaType { get; }

        /// <summary>
        /// Returns true if the response is 500 InternalServerError
        /// </summary>
        /// <returns></returns>
        bool IsInternalServerError { get; }

        /// <summary>
        /// Returns true if the response is the default response type
        /// </summary>
        /// <returns></returns>
        bool IsDefault { get; }
    }

    /// <summary>
    /// The <see cref="IPostBranchByProjectApiResponse"/>
    /// </summary>
    public interface IPostBranchByProjectApiResponse : Org.OpenAPITools.Client.IApiResponse, ICreated<Org.OpenAPITools.Model.Branch?>, IUnsupportedMediaType<Org.OpenAPITools.Model.Error?>, IInternalServerError<Org.OpenAPITools.Model.Error?>
    {
        /// <summary>
        /// Returns true if the response is 201 Created
        /// </summary>
        /// <returns></returns>
        bool IsCreated { get; }

        /// <summary>
        /// Returns true if the response is 415 UnsupportedMediaType
        /// </summary>
        /// <returns></returns>
        bool IsUnsupportedMediaType { get; }

        /// <summary>
        /// Returns true if the response is 500 InternalServerError
        /// </summary>
        /// <returns></returns>
        bool IsInternalServerError { get; }

        /// <summary>
        /// Returns true if the response is the default response type
        /// </summary>
        /// <returns></returns>
        bool IsDefault { get; }
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public class BranchApiEvents
    {
        /// <summary>
        /// The event raised after the server response
        /// </summary>
        public event EventHandler<ApiResponseEventArgs>? OnDeleteBranchByProjectAndId;

        /// <summary>
        /// The event raised after an error querying the server
        /// </summary>
        public event EventHandler<ExceptionEventArgs>? OnErrorDeleteBranchByProjectAndId;

        internal void ExecuteOnDeleteBranchByProjectAndId(BranchApi.DeleteBranchByProjectAndIdApiResponse apiResponse)
        {
            OnDeleteBranchByProjectAndId?.Invoke(this, new ApiResponseEventArgs(apiResponse));
        }

        internal void ExecuteOnErrorDeleteBranchByProjectAndId(Exception exception)
        {
            OnErrorDeleteBranchByProjectAndId?.Invoke(this, new ExceptionEventArgs(exception));
        }

        /// <summary>
        /// The event raised after the server response
        /// </summary>
        public event EventHandler<ApiResponseEventArgs>? OnGetBranchesByProject;

        /// <summary>
        /// The event raised after an error querying the server
        /// </summary>
        public event EventHandler<ExceptionEventArgs>? OnErrorGetBranchesByProject;

        internal void ExecuteOnGetBranchesByProject(BranchApi.GetBranchesByProjectApiResponse apiResponse)
        {
            OnGetBranchesByProject?.Invoke(this, new ApiResponseEventArgs(apiResponse));
        }

        internal void ExecuteOnErrorGetBranchesByProject(Exception exception)
        {
            OnErrorGetBranchesByProject?.Invoke(this, new ExceptionEventArgs(exception));
        }

        /// <summary>
        /// The event raised after the server response
        /// </summary>
        public event EventHandler<ApiResponseEventArgs>? OnGetBranchesByProjectAndId;

        /// <summary>
        /// The event raised after an error querying the server
        /// </summary>
        public event EventHandler<ExceptionEventArgs>? OnErrorGetBranchesByProjectAndId;

        internal void ExecuteOnGetBranchesByProjectAndId(BranchApi.GetBranchesByProjectAndIdApiResponse apiResponse)
        {
            OnGetBranchesByProjectAndId?.Invoke(this, new ApiResponseEventArgs(apiResponse));
        }

        internal void ExecuteOnErrorGetBranchesByProjectAndId(Exception exception)
        {
            OnErrorGetBranchesByProjectAndId?.Invoke(this, new ExceptionEventArgs(exception));
        }

        /// <summary>
        /// The event raised after the server response
        /// </summary>
        public event EventHandler<ApiResponseEventArgs>? OnPostBranchByProject;

        /// <summary>
        /// The event raised after an error querying the server
        /// </summary>
        public event EventHandler<ExceptionEventArgs>? OnErrorPostBranchByProject;

        internal void ExecuteOnPostBranchByProject(BranchApi.PostBranchByProjectApiResponse apiResponse)
        {
            OnPostBranchByProject?.Invoke(this, new ApiResponseEventArgs(apiResponse));
        }

        internal void ExecuteOnErrorPostBranchByProject(Exception exception)
        {
            OnErrorPostBranchByProject?.Invoke(this, new ExceptionEventArgs(exception));
        }
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public sealed partial class BranchApi : IBranchApi
    {
        private JsonSerializerOptions _jsonSerializerOptions;

        /// <summary>
        /// The logger factory
        /// </summary>
        public ILoggerFactory LoggerFactory { get; }

        /// <summary>
        /// The logger
        /// </summary>
        public ILogger<BranchApi> Logger { get; }

        /// <summary>
        /// The HttpClient
        /// </summary>
        public HttpClient HttpClient { get; }

        /// <summary>
        /// The class containing the events
        /// </summary>
        public BranchApiEvents Events { get; }

        /// <summary>
        /// Initializes a new instance of the <see cref="BranchApi"/> class.
        /// </summary>
        /// <returns></returns>
        public BranchApi(ILogger<BranchApi> logger, ILoggerFactory loggerFactory, HttpClient httpClient, JsonSerializerOptionsProvider jsonSerializerOptionsProvider, BranchApiEvents branchApiEvents)
        {
            _jsonSerializerOptions = jsonSerializerOptionsProvider.Options;
            LoggerFactory = loggerFactory;
            Logger = LoggerFactory.CreateLogger<BranchApi>();
            HttpClient = httpClient;
            Events = branchApiEvents;
        }

        partial void FormatDeleteBranchByProjectAndId(ref Guid projectId, ref Guid branchId);

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="projectId"></param>
        /// <param name="branchId"></param>
        private void AfterDeleteBranchByProjectAndIdDefaultImplementation(IDeleteBranchByProjectAndIdApiResponse apiResponseLocalVar, Guid projectId, Guid branchId)
        {
            bool suppressDefaultLog = false;
            AfterDeleteBranchByProjectAndId(ref suppressDefaultLog, apiResponseLocalVar, projectId, branchId);
            if (!suppressDefaultLog)
                Logger.LogInformation("{0,-9} | {1} | {3}", (apiResponseLocalVar.DownloadedAt - apiResponseLocalVar.RequestedAt).TotalSeconds, apiResponseLocalVar.StatusCode, apiResponseLocalVar.Path);
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="suppressDefaultLog"></param>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="projectId"></param>
        /// <param name="branchId"></param>
        partial void AfterDeleteBranchByProjectAndId(ref bool suppressDefaultLog, IDeleteBranchByProjectAndIdApiResponse apiResponseLocalVar, Guid projectId, Guid branchId);

        /// <summary>
        /// Logs exceptions that occur while retrieving the server response
        /// </summary>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="projectId"></param>
        /// <param name="branchId"></param>
        private void OnErrorDeleteBranchByProjectAndIdDefaultImplementation(Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, Guid projectId, Guid branchId)
        {
            bool suppressDefaultLogLocalVar = false;
            OnErrorDeleteBranchByProjectAndId(ref suppressDefaultLogLocalVar, exceptionLocalVar, pathFormatLocalVar, pathLocalVar, projectId, branchId);
            if (!suppressDefaultLogLocalVar)
                Logger.LogError(exceptionLocalVar, "An error occurred while sending the request to the server.");
        }

        /// <summary>
        /// A partial method that gives developers a way to provide customized exception handling
        /// </summary>
        /// <param name="suppressDefaultLogLocalVar"></param>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="projectId"></param>
        /// <param name="branchId"></param>
        partial void OnErrorDeleteBranchByProjectAndId(ref bool suppressDefaultLogLocalVar, Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, Guid projectId, Guid branchId);

        /// <summary>
        /// Delete branch by project and ID 
        /// </summary>
        /// <param name="projectId">ID of the project</param>
        /// <param name="branchId">ID of the branch</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IDeleteBranchByProjectAndIdApiResponse"/>&gt;</returns>
        public async Task<IDeleteBranchByProjectAndIdApiResponse?> DeleteBranchByProjectAndIdOrDefaultAsync(Guid projectId, Guid branchId, System.Threading.CancellationToken cancellationToken = default)
        {
            try
            {
                return await DeleteBranchByProjectAndIdAsync(projectId, branchId, cancellationToken).ConfigureAwait(false);
            }
            catch (Exception)
            {
                return null;
            }
        }

        /// <summary>
        /// Delete branch by project and ID 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">ID of the project</param>
        /// <param name="branchId">ID of the branch</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IDeleteBranchByProjectAndIdApiResponse"/>&gt;</returns>
        public async Task<IDeleteBranchByProjectAndIdApiResponse> DeleteBranchByProjectAndIdAsync(Guid projectId, Guid branchId, System.Threading.CancellationToken cancellationToken = default)
        {
            UriBuilder uriBuilderLocalVar = new UriBuilder();

            try
            {
                FormatDeleteBranchByProjectAndId(ref projectId, ref branchId);

                using (HttpRequestMessage httpRequestMessageLocalVar = new HttpRequestMessage())
                {
                    uriBuilderLocalVar.Host = HttpClient.BaseAddress!.Host;
                    uriBuilderLocalVar.Port = HttpClient.BaseAddress.Port;
                    uriBuilderLocalVar.Scheme = HttpClient.BaseAddress.Scheme;
                    uriBuilderLocalVar.Path = HttpClient.BaseAddress.AbsolutePath == "/"
                        ? "/projects/{projectId}/branches/{branchId}"
                        : string.Concat(HttpClient.BaseAddress.AbsolutePath, "/projects/{projectId}/branches/{branchId}");
                    uriBuilderLocalVar.Path = uriBuilderLocalVar.Path.Replace("%7BprojectId%7D", Uri.EscapeDataString(projectId.ToString()));
                    uriBuilderLocalVar.Path = uriBuilderLocalVar.Path.Replace("%7BbranchId%7D", Uri.EscapeDataString(branchId.ToString()));

                    httpRequestMessageLocalVar.RequestUri = uriBuilderLocalVar.Uri;

                    string[] acceptLocalVars = new string[] {
                        "application/json",
                        "application/ld+json"
                    };

                    string? acceptLocalVar = ClientUtils.SelectHeaderAccept(acceptLocalVars);

                    if (acceptLocalVar != null)
                        httpRequestMessageLocalVar.Headers.Accept.Add(new MediaTypeWithQualityHeaderValue(acceptLocalVar));

                    httpRequestMessageLocalVar.Method = HttpMethod.Delete;

                    DateTime requestedAtLocalVar = DateTime.UtcNow;

                    using (HttpResponseMessage httpResponseMessageLocalVar = await HttpClient.SendAsync(httpRequestMessageLocalVar, cancellationToken).ConfigureAwait(false))
                    {
                        string responseContentLocalVar = await httpResponseMessageLocalVar.Content.ReadAsStringAsync(cancellationToken).ConfigureAwait(false);

                        ILogger<DeleteBranchByProjectAndIdApiResponse> apiResponseLoggerLocalVar = LoggerFactory.CreateLogger<DeleteBranchByProjectAndIdApiResponse>();

                        DeleteBranchByProjectAndIdApiResponse apiResponseLocalVar = new(apiResponseLoggerLocalVar, httpRequestMessageLocalVar, httpResponseMessageLocalVar, responseContentLocalVar, "/projects/{projectId}/branches/{branchId}", requestedAtLocalVar, _jsonSerializerOptions);

                        AfterDeleteBranchByProjectAndIdDefaultImplementation(apiResponseLocalVar, projectId, branchId);

                        Events.ExecuteOnDeleteBranchByProjectAndId(apiResponseLocalVar);

                        return apiResponseLocalVar;
                    }
                }
            }
            catch(Exception e)
            {
                OnErrorDeleteBranchByProjectAndIdDefaultImplementation(e, "/projects/{projectId}/branches/{branchId}", uriBuilderLocalVar.Path, projectId, branchId);
                Events.ExecuteOnErrorDeleteBranchByProjectAndId(e);
                throw;
            }
        }

        /// <summary>
        /// The <see cref="DeleteBranchByProjectAndIdApiResponse"/>
        /// </summary>
        public partial class DeleteBranchByProjectAndIdApiResponse : Org.OpenAPITools.Client.ApiResponse, IDeleteBranchByProjectAndIdApiResponse
        {
            /// <summary>
            /// The logger
            /// </summary>
            public ILogger<DeleteBranchByProjectAndIdApiResponse> Logger { get; }

            /// <summary>
            /// The <see cref="DeleteBranchByProjectAndIdApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="rawContent"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public DeleteBranchByProjectAndIdApiResponse(ILogger<DeleteBranchByProjectAndIdApiResponse> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, string rawContent, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, rawContent, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            partial void OnCreated(global::System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage);

            /// <summary>
            /// Returns true if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public bool IsOk => 200 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public Org.OpenAPITools.Model.Branch? Ok()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsOk
                    ? System.Text.Json.JsonSerializer.Deserialize<Org.OpenAPITools.Model.Branch>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 200 Ok and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryOk([NotNullWhen(true)]out Org.OpenAPITools.Model.Branch? result)
            {
                result = null;

                try
                {
                    result = Ok();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)200);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 404 NotFound
            /// </summary>
            /// <returns></returns>
            public bool IsNotFound => 404 == (int)StatusCode;

            /// <summary>
            /// Returns true if the response is 415 UnsupportedMediaType
            /// </summary>
            /// <returns></returns>
            public bool IsUnsupportedMediaType => 415 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 415 UnsupportedMediaType
            /// </summary>
            /// <returns></returns>
            public Org.OpenAPITools.Model.Error? UnsupportedMediaType()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsUnsupportedMediaType
                    ? System.Text.Json.JsonSerializer.Deserialize<Org.OpenAPITools.Model.Error>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 415 UnsupportedMediaType and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryUnsupportedMediaType([NotNullWhen(true)]out Org.OpenAPITools.Model.Error? result)
            {
                result = null;

                try
                {
                    result = UnsupportedMediaType();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)415);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 500 InternalServerError
            /// </summary>
            /// <returns></returns>
            public bool IsInternalServerError => 500 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 500 InternalServerError
            /// </summary>
            /// <returns></returns>
            public Org.OpenAPITools.Model.Error? InternalServerError()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsInternalServerError
                    ? System.Text.Json.JsonSerializer.Deserialize<Org.OpenAPITools.Model.Error>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 500 InternalServerError and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryInternalServerError([NotNullWhen(true)]out Org.OpenAPITools.Model.Error? result)
            {
                result = null;

                try
                {
                    result = InternalServerError();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)500);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is the default response type
            /// </summary>
            /// <returns></returns>
            public bool IsDefault => !IsOk && !IsNotFound && !IsUnsupportedMediaType && !IsInternalServerError;

            private void OnDeserializationErrorDefaultImplementation(Exception exception, HttpStatusCode httpStatusCode)
            {
                bool suppressDefaultLog = false;
                OnDeserializationError(ref suppressDefaultLog, exception, httpStatusCode);
                if (!suppressDefaultLog)
                    Logger.LogError(exception, "An error occurred while deserializing the {code} response.", httpStatusCode);
            }

            partial void OnDeserializationError(ref bool suppressDefaultLog, Exception exception, HttpStatusCode httpStatusCode);
        }

        partial void FormatGetBranchesByProject(ref Guid projectId, ref Option<string> pageAfter, ref Option<string> pageBefore, ref Option<int> pageSize);

        /// <summary>
        /// Validates the request parameters
        /// </summary>
        /// <param name="pageAfter"></param>
        /// <param name="pageBefore"></param>
        /// <returns></returns>
        private void ValidateGetBranchesByProject(Option<string> pageAfter, Option<string> pageBefore)
        {
            if (pageAfter.IsSet && pageAfter.Value == null)
                throw new ArgumentNullException(nameof(pageAfter));

            if (pageBefore.IsSet && pageBefore.Value == null)
                throw new ArgumentNullException(nameof(pageBefore));
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="projectId"></param>
        /// <param name="pageAfter"></param>
        /// <param name="pageBefore"></param>
        /// <param name="pageSize"></param>
        private void AfterGetBranchesByProjectDefaultImplementation(IGetBranchesByProjectApiResponse apiResponseLocalVar, Guid projectId, Option<string> pageAfter, Option<string> pageBefore, Option<int> pageSize)
        {
            bool suppressDefaultLog = false;
            AfterGetBranchesByProject(ref suppressDefaultLog, apiResponseLocalVar, projectId, pageAfter, pageBefore, pageSize);
            if (!suppressDefaultLog)
                Logger.LogInformation("{0,-9} | {1} | {3}", (apiResponseLocalVar.DownloadedAt - apiResponseLocalVar.RequestedAt).TotalSeconds, apiResponseLocalVar.StatusCode, apiResponseLocalVar.Path);
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="suppressDefaultLog"></param>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="projectId"></param>
        /// <param name="pageAfter"></param>
        /// <param name="pageBefore"></param>
        /// <param name="pageSize"></param>
        partial void AfterGetBranchesByProject(ref bool suppressDefaultLog, IGetBranchesByProjectApiResponse apiResponseLocalVar, Guid projectId, Option<string> pageAfter, Option<string> pageBefore, Option<int> pageSize);

        /// <summary>
        /// Logs exceptions that occur while retrieving the server response
        /// </summary>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="projectId"></param>
        /// <param name="pageAfter"></param>
        /// <param name="pageBefore"></param>
        /// <param name="pageSize"></param>
        private void OnErrorGetBranchesByProjectDefaultImplementation(Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, Guid projectId, Option<string> pageAfter, Option<string> pageBefore, Option<int> pageSize)
        {
            bool suppressDefaultLogLocalVar = false;
            OnErrorGetBranchesByProject(ref suppressDefaultLogLocalVar, exceptionLocalVar, pathFormatLocalVar, pathLocalVar, projectId, pageAfter, pageBefore, pageSize);
            if (!suppressDefaultLogLocalVar)
                Logger.LogError(exceptionLocalVar, "An error occurred while sending the request to the server.");
        }

        /// <summary>
        /// A partial method that gives developers a way to provide customized exception handling
        /// </summary>
        /// <param name="suppressDefaultLogLocalVar"></param>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="projectId"></param>
        /// <param name="pageAfter"></param>
        /// <param name="pageBefore"></param>
        /// <param name="pageSize"></param>
        partial void OnErrorGetBranchesByProject(ref bool suppressDefaultLogLocalVar, Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, Guid projectId, Option<string> pageAfter, Option<string> pageBefore, Option<int> pageSize);

        /// <summary>
        /// Get branches by project 
        /// </summary>
        /// <param name="projectId">ID of the project</param>
        /// <param name="pageAfter">Page after (optional)</param>
        /// <param name="pageBefore">Page before (optional)</param>
        /// <param name="pageSize">Page size (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IGetBranchesByProjectApiResponse"/>&gt;</returns>
        public async Task<IGetBranchesByProjectApiResponse?> GetBranchesByProjectOrDefaultAsync(Guid projectId, Option<string> pageAfter = default, Option<string> pageBefore = default, Option<int> pageSize = default, System.Threading.CancellationToken cancellationToken = default)
        {
            try
            {
                return await GetBranchesByProjectAsync(projectId, pageAfter, pageBefore, pageSize, cancellationToken).ConfigureAwait(false);
            }
            catch (Exception)
            {
                return null;
            }
        }

        /// <summary>
        /// Get branches by project 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">ID of the project</param>
        /// <param name="pageAfter">Page after (optional)</param>
        /// <param name="pageBefore">Page before (optional)</param>
        /// <param name="pageSize">Page size (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IGetBranchesByProjectApiResponse"/>&gt;</returns>
        public async Task<IGetBranchesByProjectApiResponse> GetBranchesByProjectAsync(Guid projectId, Option<string> pageAfter = default, Option<string> pageBefore = default, Option<int> pageSize = default, System.Threading.CancellationToken cancellationToken = default)
        {
            UriBuilder uriBuilderLocalVar = new UriBuilder();

            try
            {
                ValidateGetBranchesByProject(pageAfter, pageBefore);

                FormatGetBranchesByProject(ref projectId, ref pageAfter, ref pageBefore, ref pageSize);

                using (HttpRequestMessage httpRequestMessageLocalVar = new HttpRequestMessage())
                {
                    uriBuilderLocalVar.Host = HttpClient.BaseAddress!.Host;
                    uriBuilderLocalVar.Port = HttpClient.BaseAddress.Port;
                    uriBuilderLocalVar.Scheme = HttpClient.BaseAddress.Scheme;
                    uriBuilderLocalVar.Path = HttpClient.BaseAddress.AbsolutePath == "/"
                        ? "/projects/{projectId}/branches"
                        : string.Concat(HttpClient.BaseAddress.AbsolutePath, "/projects/{projectId}/branches");
                    uriBuilderLocalVar.Path = uriBuilderLocalVar.Path.Replace("%7BprojectId%7D", Uri.EscapeDataString(projectId.ToString()));

                    System.Collections.Specialized.NameValueCollection parseQueryStringLocalVar = System.Web.HttpUtility.ParseQueryString(string.Empty);

                    if (pageAfter.IsSet)
                        parseQueryStringLocalVar["page[after]"] = ClientUtils.ParameterToString(pageAfter.Value);

                    if (pageBefore.IsSet)
                        parseQueryStringLocalVar["page[before]"] = ClientUtils.ParameterToString(pageBefore.Value);

                    if (pageSize.IsSet)
                        parseQueryStringLocalVar["page[size]"] = ClientUtils.ParameterToString(pageSize.Value);

                    uriBuilderLocalVar.Query = parseQueryStringLocalVar.ToString();

                    httpRequestMessageLocalVar.RequestUri = uriBuilderLocalVar.Uri;

                    string[] acceptLocalVars = new string[] {
                        "application/json",
                        "application/ld+json"
                    };

                    string? acceptLocalVar = ClientUtils.SelectHeaderAccept(acceptLocalVars);

                    if (acceptLocalVar != null)
                        httpRequestMessageLocalVar.Headers.Accept.Add(new MediaTypeWithQualityHeaderValue(acceptLocalVar));

                    httpRequestMessageLocalVar.Method = HttpMethod.Get;

                    DateTime requestedAtLocalVar = DateTime.UtcNow;

                    using (HttpResponseMessage httpResponseMessageLocalVar = await HttpClient.SendAsync(httpRequestMessageLocalVar, cancellationToken).ConfigureAwait(false))
                    {
                        string responseContentLocalVar = await httpResponseMessageLocalVar.Content.ReadAsStringAsync(cancellationToken).ConfigureAwait(false);

                        ILogger<GetBranchesByProjectApiResponse> apiResponseLoggerLocalVar = LoggerFactory.CreateLogger<GetBranchesByProjectApiResponse>();

                        GetBranchesByProjectApiResponse apiResponseLocalVar = new(apiResponseLoggerLocalVar, httpRequestMessageLocalVar, httpResponseMessageLocalVar, responseContentLocalVar, "/projects/{projectId}/branches", requestedAtLocalVar, _jsonSerializerOptions);

                        AfterGetBranchesByProjectDefaultImplementation(apiResponseLocalVar, projectId, pageAfter, pageBefore, pageSize);

                        Events.ExecuteOnGetBranchesByProject(apiResponseLocalVar);

                        return apiResponseLocalVar;
                    }
                }
            }
            catch(Exception e)
            {
                OnErrorGetBranchesByProjectDefaultImplementation(e, "/projects/{projectId}/branches", uriBuilderLocalVar.Path, projectId, pageAfter, pageBefore, pageSize);
                Events.ExecuteOnErrorGetBranchesByProject(e);
                throw;
            }
        }

        /// <summary>
        /// The <see cref="GetBranchesByProjectApiResponse"/>
        /// </summary>
        public partial class GetBranchesByProjectApiResponse : Org.OpenAPITools.Client.ApiResponse, IGetBranchesByProjectApiResponse
        {
            /// <summary>
            /// The logger
            /// </summary>
            public ILogger<GetBranchesByProjectApiResponse> Logger { get; }

            /// <summary>
            /// The <see cref="GetBranchesByProjectApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="rawContent"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public GetBranchesByProjectApiResponse(ILogger<GetBranchesByProjectApiResponse> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, string rawContent, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, rawContent, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            partial void OnCreated(global::System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage);

            /// <summary>
            /// Returns true if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public bool IsOk => 200 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public List<Branch>? Ok()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsOk
                    ? System.Text.Json.JsonSerializer.Deserialize<List<Branch>>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 200 Ok and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryOk([NotNullWhen(true)]out List<Branch>? result)
            {
                result = null;

                try
                {
                    result = Ok();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)200);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 404 NotFound
            /// </summary>
            /// <returns></returns>
            public bool IsNotFound => 404 == (int)StatusCode;

            /// <summary>
            /// Returns true if the response is 415 UnsupportedMediaType
            /// </summary>
            /// <returns></returns>
            public bool IsUnsupportedMediaType => 415 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 415 UnsupportedMediaType
            /// </summary>
            /// <returns></returns>
            public Org.OpenAPITools.Model.Error? UnsupportedMediaType()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsUnsupportedMediaType
                    ? System.Text.Json.JsonSerializer.Deserialize<Org.OpenAPITools.Model.Error>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 415 UnsupportedMediaType and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryUnsupportedMediaType([NotNullWhen(true)]out Org.OpenAPITools.Model.Error? result)
            {
                result = null;

                try
                {
                    result = UnsupportedMediaType();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)415);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 500 InternalServerError
            /// </summary>
            /// <returns></returns>
            public bool IsInternalServerError => 500 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 500 InternalServerError
            /// </summary>
            /// <returns></returns>
            public Org.OpenAPITools.Model.Error? InternalServerError()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsInternalServerError
                    ? System.Text.Json.JsonSerializer.Deserialize<Org.OpenAPITools.Model.Error>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 500 InternalServerError and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryInternalServerError([NotNullWhen(true)]out Org.OpenAPITools.Model.Error? result)
            {
                result = null;

                try
                {
                    result = InternalServerError();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)500);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is the default response type
            /// </summary>
            /// <returns></returns>
            public bool IsDefault => !IsOk && !IsNotFound && !IsUnsupportedMediaType && !IsInternalServerError;

            private void OnDeserializationErrorDefaultImplementation(Exception exception, HttpStatusCode httpStatusCode)
            {
                bool suppressDefaultLog = false;
                OnDeserializationError(ref suppressDefaultLog, exception, httpStatusCode);
                if (!suppressDefaultLog)
                    Logger.LogError(exception, "An error occurred while deserializing the {code} response.", httpStatusCode);
            }

            partial void OnDeserializationError(ref bool suppressDefaultLog, Exception exception, HttpStatusCode httpStatusCode);
        }

        partial void FormatGetBranchesByProjectAndId(ref Guid projectId, ref Guid branchId);

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="projectId"></param>
        /// <param name="branchId"></param>
        private void AfterGetBranchesByProjectAndIdDefaultImplementation(IGetBranchesByProjectAndIdApiResponse apiResponseLocalVar, Guid projectId, Guid branchId)
        {
            bool suppressDefaultLog = false;
            AfterGetBranchesByProjectAndId(ref suppressDefaultLog, apiResponseLocalVar, projectId, branchId);
            if (!suppressDefaultLog)
                Logger.LogInformation("{0,-9} | {1} | {3}", (apiResponseLocalVar.DownloadedAt - apiResponseLocalVar.RequestedAt).TotalSeconds, apiResponseLocalVar.StatusCode, apiResponseLocalVar.Path);
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="suppressDefaultLog"></param>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="projectId"></param>
        /// <param name="branchId"></param>
        partial void AfterGetBranchesByProjectAndId(ref bool suppressDefaultLog, IGetBranchesByProjectAndIdApiResponse apiResponseLocalVar, Guid projectId, Guid branchId);

        /// <summary>
        /// Logs exceptions that occur while retrieving the server response
        /// </summary>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="projectId"></param>
        /// <param name="branchId"></param>
        private void OnErrorGetBranchesByProjectAndIdDefaultImplementation(Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, Guid projectId, Guid branchId)
        {
            bool suppressDefaultLogLocalVar = false;
            OnErrorGetBranchesByProjectAndId(ref suppressDefaultLogLocalVar, exceptionLocalVar, pathFormatLocalVar, pathLocalVar, projectId, branchId);
            if (!suppressDefaultLogLocalVar)
                Logger.LogError(exceptionLocalVar, "An error occurred while sending the request to the server.");
        }

        /// <summary>
        /// A partial method that gives developers a way to provide customized exception handling
        /// </summary>
        /// <param name="suppressDefaultLogLocalVar"></param>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="projectId"></param>
        /// <param name="branchId"></param>
        partial void OnErrorGetBranchesByProjectAndId(ref bool suppressDefaultLogLocalVar, Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, Guid projectId, Guid branchId);

        /// <summary>
        /// Get branch by project and ID 
        /// </summary>
        /// <param name="projectId">ID of the project</param>
        /// <param name="branchId">ID of the branch</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IGetBranchesByProjectAndIdApiResponse"/>&gt;</returns>
        public async Task<IGetBranchesByProjectAndIdApiResponse?> GetBranchesByProjectAndIdOrDefaultAsync(Guid projectId, Guid branchId, System.Threading.CancellationToken cancellationToken = default)
        {
            try
            {
                return await GetBranchesByProjectAndIdAsync(projectId, branchId, cancellationToken).ConfigureAwait(false);
            }
            catch (Exception)
            {
                return null;
            }
        }

        /// <summary>
        /// Get branch by project and ID 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">ID of the project</param>
        /// <param name="branchId">ID of the branch</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IGetBranchesByProjectAndIdApiResponse"/>&gt;</returns>
        public async Task<IGetBranchesByProjectAndIdApiResponse> GetBranchesByProjectAndIdAsync(Guid projectId, Guid branchId, System.Threading.CancellationToken cancellationToken = default)
        {
            UriBuilder uriBuilderLocalVar = new UriBuilder();

            try
            {
                FormatGetBranchesByProjectAndId(ref projectId, ref branchId);

                using (HttpRequestMessage httpRequestMessageLocalVar = new HttpRequestMessage())
                {
                    uriBuilderLocalVar.Host = HttpClient.BaseAddress!.Host;
                    uriBuilderLocalVar.Port = HttpClient.BaseAddress.Port;
                    uriBuilderLocalVar.Scheme = HttpClient.BaseAddress.Scheme;
                    uriBuilderLocalVar.Path = HttpClient.BaseAddress.AbsolutePath == "/"
                        ? "/projects/{projectId}/branches/{branchId}"
                        : string.Concat(HttpClient.BaseAddress.AbsolutePath, "/projects/{projectId}/branches/{branchId}");
                    uriBuilderLocalVar.Path = uriBuilderLocalVar.Path.Replace("%7BprojectId%7D", Uri.EscapeDataString(projectId.ToString()));
                    uriBuilderLocalVar.Path = uriBuilderLocalVar.Path.Replace("%7BbranchId%7D", Uri.EscapeDataString(branchId.ToString()));

                    httpRequestMessageLocalVar.RequestUri = uriBuilderLocalVar.Uri;

                    string[] acceptLocalVars = new string[] {
                        "application/json",
                        "application/ld+json"
                    };

                    string? acceptLocalVar = ClientUtils.SelectHeaderAccept(acceptLocalVars);

                    if (acceptLocalVar != null)
                        httpRequestMessageLocalVar.Headers.Accept.Add(new MediaTypeWithQualityHeaderValue(acceptLocalVar));

                    httpRequestMessageLocalVar.Method = HttpMethod.Get;

                    DateTime requestedAtLocalVar = DateTime.UtcNow;

                    using (HttpResponseMessage httpResponseMessageLocalVar = await HttpClient.SendAsync(httpRequestMessageLocalVar, cancellationToken).ConfigureAwait(false))
                    {
                        string responseContentLocalVar = await httpResponseMessageLocalVar.Content.ReadAsStringAsync(cancellationToken).ConfigureAwait(false);

                        ILogger<GetBranchesByProjectAndIdApiResponse> apiResponseLoggerLocalVar = LoggerFactory.CreateLogger<GetBranchesByProjectAndIdApiResponse>();

                        GetBranchesByProjectAndIdApiResponse apiResponseLocalVar = new(apiResponseLoggerLocalVar, httpRequestMessageLocalVar, httpResponseMessageLocalVar, responseContentLocalVar, "/projects/{projectId}/branches/{branchId}", requestedAtLocalVar, _jsonSerializerOptions);

                        AfterGetBranchesByProjectAndIdDefaultImplementation(apiResponseLocalVar, projectId, branchId);

                        Events.ExecuteOnGetBranchesByProjectAndId(apiResponseLocalVar);

                        return apiResponseLocalVar;
                    }
                }
            }
            catch(Exception e)
            {
                OnErrorGetBranchesByProjectAndIdDefaultImplementation(e, "/projects/{projectId}/branches/{branchId}", uriBuilderLocalVar.Path, projectId, branchId);
                Events.ExecuteOnErrorGetBranchesByProjectAndId(e);
                throw;
            }
        }

        /// <summary>
        /// The <see cref="GetBranchesByProjectAndIdApiResponse"/>
        /// </summary>
        public partial class GetBranchesByProjectAndIdApiResponse : Org.OpenAPITools.Client.ApiResponse, IGetBranchesByProjectAndIdApiResponse
        {
            /// <summary>
            /// The logger
            /// </summary>
            public ILogger<GetBranchesByProjectAndIdApiResponse> Logger { get; }

            /// <summary>
            /// The <see cref="GetBranchesByProjectAndIdApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="rawContent"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public GetBranchesByProjectAndIdApiResponse(ILogger<GetBranchesByProjectAndIdApiResponse> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, string rawContent, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, rawContent, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            partial void OnCreated(global::System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage);

            /// <summary>
            /// Returns true if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public bool IsOk => 200 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public Org.OpenAPITools.Model.Branch? Ok()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsOk
                    ? System.Text.Json.JsonSerializer.Deserialize<Org.OpenAPITools.Model.Branch>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 200 Ok and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryOk([NotNullWhen(true)]out Org.OpenAPITools.Model.Branch? result)
            {
                result = null;

                try
                {
                    result = Ok();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)200);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 404 NotFound
            /// </summary>
            /// <returns></returns>
            public bool IsNotFound => 404 == (int)StatusCode;

            /// <summary>
            /// Returns true if the response is 415 UnsupportedMediaType
            /// </summary>
            /// <returns></returns>
            public bool IsUnsupportedMediaType => 415 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 415 UnsupportedMediaType
            /// </summary>
            /// <returns></returns>
            public Org.OpenAPITools.Model.Error? UnsupportedMediaType()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsUnsupportedMediaType
                    ? System.Text.Json.JsonSerializer.Deserialize<Org.OpenAPITools.Model.Error>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 415 UnsupportedMediaType and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryUnsupportedMediaType([NotNullWhen(true)]out Org.OpenAPITools.Model.Error? result)
            {
                result = null;

                try
                {
                    result = UnsupportedMediaType();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)415);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 500 InternalServerError
            /// </summary>
            /// <returns></returns>
            public bool IsInternalServerError => 500 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 500 InternalServerError
            /// </summary>
            /// <returns></returns>
            public Org.OpenAPITools.Model.Error? InternalServerError()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsInternalServerError
                    ? System.Text.Json.JsonSerializer.Deserialize<Org.OpenAPITools.Model.Error>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 500 InternalServerError and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryInternalServerError([NotNullWhen(true)]out Org.OpenAPITools.Model.Error? result)
            {
                result = null;

                try
                {
                    result = InternalServerError();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)500);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is the default response type
            /// </summary>
            /// <returns></returns>
            public bool IsDefault => !IsOk && !IsNotFound && !IsUnsupportedMediaType && !IsInternalServerError;

            private void OnDeserializationErrorDefaultImplementation(Exception exception, HttpStatusCode httpStatusCode)
            {
                bool suppressDefaultLog = false;
                OnDeserializationError(ref suppressDefaultLog, exception, httpStatusCode);
                if (!suppressDefaultLog)
                    Logger.LogError(exception, "An error occurred while deserializing the {code} response.", httpStatusCode);
            }

            partial void OnDeserializationError(ref bool suppressDefaultLog, Exception exception, HttpStatusCode httpStatusCode);
        }

        partial void FormatPostBranchByProject(ref Guid projectId, Branch body);

        /// <summary>
        /// Validates the request parameters
        /// </summary>
        /// <param name="body"></param>
        /// <returns></returns>
        private void ValidatePostBranchByProject(Branch body)
        {
            if (body == null)
                throw new ArgumentNullException(nameof(body));
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="projectId"></param>
        /// <param name="body"></param>
        private void AfterPostBranchByProjectDefaultImplementation(IPostBranchByProjectApiResponse apiResponseLocalVar, Guid projectId, Branch body)
        {
            bool suppressDefaultLog = false;
            AfterPostBranchByProject(ref suppressDefaultLog, apiResponseLocalVar, projectId, body);
            if (!suppressDefaultLog)
                Logger.LogInformation("{0,-9} | {1} | {3}", (apiResponseLocalVar.DownloadedAt - apiResponseLocalVar.RequestedAt).TotalSeconds, apiResponseLocalVar.StatusCode, apiResponseLocalVar.Path);
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="suppressDefaultLog"></param>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="projectId"></param>
        /// <param name="body"></param>
        partial void AfterPostBranchByProject(ref bool suppressDefaultLog, IPostBranchByProjectApiResponse apiResponseLocalVar, Guid projectId, Branch body);

        /// <summary>
        /// Logs exceptions that occur while retrieving the server response
        /// </summary>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="projectId"></param>
        /// <param name="body"></param>
        private void OnErrorPostBranchByProjectDefaultImplementation(Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, Guid projectId, Branch body)
        {
            bool suppressDefaultLogLocalVar = false;
            OnErrorPostBranchByProject(ref suppressDefaultLogLocalVar, exceptionLocalVar, pathFormatLocalVar, pathLocalVar, projectId, body);
            if (!suppressDefaultLogLocalVar)
                Logger.LogError(exceptionLocalVar, "An error occurred while sending the request to the server.");
        }

        /// <summary>
        /// A partial method that gives developers a way to provide customized exception handling
        /// </summary>
        /// <param name="suppressDefaultLogLocalVar"></param>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="projectId"></param>
        /// <param name="body"></param>
        partial void OnErrorPostBranchByProject(ref bool suppressDefaultLogLocalVar, Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, Guid projectId, Branch body);

        /// <summary>
        /// Create branch by project 
        /// </summary>
        /// <param name="projectId">ID of the project</param>
        /// <param name="body"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IPostBranchByProjectApiResponse"/>&gt;</returns>
        public async Task<IPostBranchByProjectApiResponse?> PostBranchByProjectOrDefaultAsync(Guid projectId, Branch body, System.Threading.CancellationToken cancellationToken = default)
        {
            try
            {
                return await PostBranchByProjectAsync(projectId, body, cancellationToken).ConfigureAwait(false);
            }
            catch (Exception)
            {
                return null;
            }
        }

        /// <summary>
        /// Create branch by project 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">ID of the project</param>
        /// <param name="body"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IPostBranchByProjectApiResponse"/>&gt;</returns>
        public async Task<IPostBranchByProjectApiResponse> PostBranchByProjectAsync(Guid projectId, Branch body, System.Threading.CancellationToken cancellationToken = default)
        {
            UriBuilder uriBuilderLocalVar = new UriBuilder();

            try
            {
                ValidatePostBranchByProject(body);

                FormatPostBranchByProject(ref projectId, body);

                using (HttpRequestMessage httpRequestMessageLocalVar = new HttpRequestMessage())
                {
                    uriBuilderLocalVar.Host = HttpClient.BaseAddress!.Host;
                    uriBuilderLocalVar.Port = HttpClient.BaseAddress.Port;
                    uriBuilderLocalVar.Scheme = HttpClient.BaseAddress.Scheme;
                    uriBuilderLocalVar.Path = HttpClient.BaseAddress.AbsolutePath == "/"
                        ? "/projects/{projectId}/branches"
                        : string.Concat(HttpClient.BaseAddress.AbsolutePath, "/projects/{projectId}/branches");
                    uriBuilderLocalVar.Path = uriBuilderLocalVar.Path.Replace("%7BprojectId%7D", Uri.EscapeDataString(projectId.ToString()));

                    httpRequestMessageLocalVar.Content = (body as object) is System.IO.Stream stream
                        ? httpRequestMessageLocalVar.Content = new StreamContent(stream)
                        : httpRequestMessageLocalVar.Content = new StringContent(JsonSerializer.Serialize(body, _jsonSerializerOptions));

                    httpRequestMessageLocalVar.RequestUri = uriBuilderLocalVar.Uri;

                    string[] contentTypes = new string[] {
                        "application/json"
                    };

                    string? contentTypeLocalVar = ClientUtils.SelectHeaderContentType(contentTypes);

                    if (contentTypeLocalVar != null && httpRequestMessageLocalVar.Content != null)
                        httpRequestMessageLocalVar.Content.Headers.ContentType = new MediaTypeHeaderValue(contentTypeLocalVar);

                    string[] acceptLocalVars = new string[] {
                        "application/json",
                        "application/ld+json"
                    };

                    string? acceptLocalVar = ClientUtils.SelectHeaderAccept(acceptLocalVars);

                    if (acceptLocalVar != null)
                        httpRequestMessageLocalVar.Headers.Accept.Add(new MediaTypeWithQualityHeaderValue(acceptLocalVar));

                    httpRequestMessageLocalVar.Method = HttpMethod.Post;

                    DateTime requestedAtLocalVar = DateTime.UtcNow;

                    using (HttpResponseMessage httpResponseMessageLocalVar = await HttpClient.SendAsync(httpRequestMessageLocalVar, cancellationToken).ConfigureAwait(false))
                    {
                        string responseContentLocalVar = await httpResponseMessageLocalVar.Content.ReadAsStringAsync(cancellationToken).ConfigureAwait(false);

                        ILogger<PostBranchByProjectApiResponse> apiResponseLoggerLocalVar = LoggerFactory.CreateLogger<PostBranchByProjectApiResponse>();

                        PostBranchByProjectApiResponse apiResponseLocalVar = new(apiResponseLoggerLocalVar, httpRequestMessageLocalVar, httpResponseMessageLocalVar, responseContentLocalVar, "/projects/{projectId}/branches", requestedAtLocalVar, _jsonSerializerOptions);

                        AfterPostBranchByProjectDefaultImplementation(apiResponseLocalVar, projectId, body);

                        Events.ExecuteOnPostBranchByProject(apiResponseLocalVar);

                        return apiResponseLocalVar;
                    }
                }
            }
            catch(Exception e)
            {
                OnErrorPostBranchByProjectDefaultImplementation(e, "/projects/{projectId}/branches", uriBuilderLocalVar.Path, projectId, body);
                Events.ExecuteOnErrorPostBranchByProject(e);
                throw;
            }
        }

        /// <summary>
        /// The <see cref="PostBranchByProjectApiResponse"/>
        /// </summary>
        public partial class PostBranchByProjectApiResponse : Org.OpenAPITools.Client.ApiResponse, IPostBranchByProjectApiResponse
        {
            /// <summary>
            /// The logger
            /// </summary>
            public ILogger<PostBranchByProjectApiResponse> Logger { get; }

            /// <summary>
            /// The <see cref="PostBranchByProjectApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="rawContent"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public PostBranchByProjectApiResponse(ILogger<PostBranchByProjectApiResponse> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, string rawContent, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, rawContent, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            partial void OnCreated(global::System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage);

            /// <summary>
            /// Returns true if the response is 201 Created
            /// </summary>
            /// <returns></returns>
            public bool IsCreated => 201 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 201 Created
            /// </summary>
            /// <returns></returns>
            public Org.OpenAPITools.Model.Branch? Created()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsCreated
                    ? System.Text.Json.JsonSerializer.Deserialize<Org.OpenAPITools.Model.Branch>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 201 Created and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryCreated([NotNullWhen(true)]out Org.OpenAPITools.Model.Branch? result)
            {
                result = null;

                try
                {
                    result = Created();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)201);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 415 UnsupportedMediaType
            /// </summary>
            /// <returns></returns>
            public bool IsUnsupportedMediaType => 415 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 415 UnsupportedMediaType
            /// </summary>
            /// <returns></returns>
            public Org.OpenAPITools.Model.Error? UnsupportedMediaType()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsUnsupportedMediaType
                    ? System.Text.Json.JsonSerializer.Deserialize<Org.OpenAPITools.Model.Error>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 415 UnsupportedMediaType and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryUnsupportedMediaType([NotNullWhen(true)]out Org.OpenAPITools.Model.Error? result)
            {
                result = null;

                try
                {
                    result = UnsupportedMediaType();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)415);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 500 InternalServerError
            /// </summary>
            /// <returns></returns>
            public bool IsInternalServerError => 500 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 500 InternalServerError
            /// </summary>
            /// <returns></returns>
            public Org.OpenAPITools.Model.Error? InternalServerError()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsInternalServerError
                    ? System.Text.Json.JsonSerializer.Deserialize<Org.OpenAPITools.Model.Error>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 500 InternalServerError and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryInternalServerError([NotNullWhen(true)]out Org.OpenAPITools.Model.Error? result)
            {
                result = null;

                try
                {
                    result = InternalServerError();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)500);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is the default response type
            /// </summary>
            /// <returns></returns>
            public bool IsDefault => !IsCreated && !IsUnsupportedMediaType && !IsInternalServerError;

            private void OnDeserializationErrorDefaultImplementation(Exception exception, HttpStatusCode httpStatusCode)
            {
                bool suppressDefaultLog = false;
                OnDeserializationError(ref suppressDefaultLog, exception, httpStatusCode);
                if (!suppressDefaultLog)
                    Logger.LogError(exception, "An error occurred while deserializing the {code} response.", httpStatusCode);
            }

            partial void OnDeserializationError(ref bool suppressDefaultLog, Exception exception, HttpStatusCode httpStatusCode);
        }
    }
}
