// <auto-generated>
/*
 * SysML v2 API and Services
 *
 * REST/HTTP binding (PSM) for the SysML v2 standard API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections.Generic;
using System.Net;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text.Json;
using Org.OpenAPITools.Client;
using Org.OpenAPITools.Model;
using System.Diagnostics.CodeAnalysis;

namespace Org.OpenAPITools.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// This class is registered as transient.
    /// </summary>
    public interface ICommitApi : IApi
    {
        /// <summary>
        /// The class containing the events
        /// </summary>
        CommitApiEvents Events { get; }

        /// <summary>
        /// Get commit by project and ID
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">ID of the project</param>
        /// <param name="commitId">ID of the commit</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IGetCommitByProjectAndIdApiResponse"/>&gt;</returns>
        Task<IGetCommitByProjectAndIdApiResponse> GetCommitByProjectAndIdAsync(Guid projectId, Guid commitId, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Get commit by project and ID
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <param name="projectId">ID of the project</param>
        /// <param name="commitId">ID of the commit</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IGetCommitByProjectAndIdApiResponse"/>?&gt;</returns>
        Task<IGetCommitByProjectAndIdApiResponse?> GetCommitByProjectAndIdOrDefaultAsync(Guid projectId, Guid commitId, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Get commits by project
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">ID of the project</param>
        /// <param name="pageAfter">Page after (optional)</param>
        /// <param name="pageBefore">Page before (optional)</param>
        /// <param name="pageSize">Page size (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IGetCommitsByProjectApiResponse"/>&gt;</returns>
        Task<IGetCommitsByProjectApiResponse> GetCommitsByProjectAsync(Guid projectId, Option<string> pageAfter = default, Option<string> pageBefore = default, Option<int> pageSize = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Get commits by project
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <param name="projectId">ID of the project</param>
        /// <param name="pageAfter">Page after (optional)</param>
        /// <param name="pageBefore">Page before (optional)</param>
        /// <param name="pageSize">Page size (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IGetCommitsByProjectApiResponse"/>?&gt;</returns>
        Task<IGetCommitsByProjectApiResponse?> GetCommitsByProjectOrDefaultAsync(Guid projectId, Option<string> pageAfter = default, Option<string> pageBefore = default, Option<int> pageSize = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Create commit by project
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">ID of the project</param>
        /// <param name="body"></param>
        /// <param name="branchId">ID of the branch - project&#39;s default branch if unspecified (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IPostCommitByProjectApiResponse"/>&gt;</returns>
        Task<IPostCommitByProjectApiResponse> PostCommitByProjectAsync(Guid projectId, Commit body, Option<Guid> branchId = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Create commit by project
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <param name="projectId">ID of the project</param>
        /// <param name="body"></param>
        /// <param name="branchId">ID of the branch - project&#39;s default branch if unspecified (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IPostCommitByProjectApiResponse"/>?&gt;</returns>
        Task<IPostCommitByProjectApiResponse?> PostCommitByProjectOrDefaultAsync(Guid projectId, Commit body, Option<Guid> branchId = default, System.Threading.CancellationToken cancellationToken = default);
    }

    /// <summary>
    /// The <see cref="IGetCommitByProjectAndIdApiResponse"/>
    /// </summary>
    public interface IGetCommitByProjectAndIdApiResponse : Org.OpenAPITools.Client.IApiResponse, IOk<Org.OpenAPITools.Model.Commit?>, IUnsupportedMediaType<Org.OpenAPITools.Model.Error?>, IInternalServerError<Org.OpenAPITools.Model.Error?>
    {
        /// <summary>
        /// Returns true if the response is 200 Ok
        /// </summary>
        /// <returns></returns>
        bool IsOk { get; }

        /// <summary>
        /// Returns true if the response is 404 NotFound
        /// </summary>
        /// <returns></returns>
        bool IsNotFound { get; }

        /// <summary>
        /// Returns true if the response is 415 UnsupportedMediaType
        /// </summary>
        /// <returns></returns>
        bool IsUnsupportedMediaType { get; }

        /// <summary>
        /// Returns true if the response is 500 InternalServerError
        /// </summary>
        /// <returns></returns>
        bool IsInternalServerError { get; }

        /// <summary>
        /// Returns true if the response is the default response type
        /// </summary>
        /// <returns></returns>
        bool IsDefault { get; }
    }

    /// <summary>
    /// The <see cref="IGetCommitsByProjectApiResponse"/>
    /// </summary>
    public interface IGetCommitsByProjectApiResponse : Org.OpenAPITools.Client.IApiResponse, IOk<List<Commit>?>, IUnsupportedMediaType<Org.OpenAPITools.Model.Error?>, IInternalServerError<Org.OpenAPITools.Model.Error?>
    {
        /// <summary>
        /// Returns true if the response is 200 Ok
        /// </summary>
        /// <returns></returns>
        bool IsOk { get; }

        /// <summary>
        /// Returns true if the response is 404 NotFound
        /// </summary>
        /// <returns></returns>
        bool IsNotFound { get; }

        /// <summary>
        /// Returns true if the response is 415 UnsupportedMediaType
        /// </summary>
        /// <returns></returns>
        bool IsUnsupportedMediaType { get; }

        /// <summary>
        /// Returns true if the response is 500 InternalServerError
        /// </summary>
        /// <returns></returns>
        bool IsInternalServerError { get; }

        /// <summary>
        /// Returns true if the response is the default response type
        /// </summary>
        /// <returns></returns>
        bool IsDefault { get; }
    }

    /// <summary>
    /// The <see cref="IPostCommitByProjectApiResponse"/>
    /// </summary>
    public interface IPostCommitByProjectApiResponse : Org.OpenAPITools.Client.IApiResponse, ICreated<Org.OpenAPITools.Model.Commit?>, IUnsupportedMediaType<Org.OpenAPITools.Model.Error?>, IInternalServerError<Org.OpenAPITools.Model.Error?>
    {
        /// <summary>
        /// Returns true if the response is 201 Created
        /// </summary>
        /// <returns></returns>
        bool IsCreated { get; }

        /// <summary>
        /// Returns true if the response is 415 UnsupportedMediaType
        /// </summary>
        /// <returns></returns>
        bool IsUnsupportedMediaType { get; }

        /// <summary>
        /// Returns true if the response is 500 InternalServerError
        /// </summary>
        /// <returns></returns>
        bool IsInternalServerError { get; }

        /// <summary>
        /// Returns true if the response is the default response type
        /// </summary>
        /// <returns></returns>
        bool IsDefault { get; }
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public class CommitApiEvents
    {
        /// <summary>
        /// The event raised after the server response
        /// </summary>
        public event EventHandler<ApiResponseEventArgs>? OnGetCommitByProjectAndId;

        /// <summary>
        /// The event raised after an error querying the server
        /// </summary>
        public event EventHandler<ExceptionEventArgs>? OnErrorGetCommitByProjectAndId;

        internal void ExecuteOnGetCommitByProjectAndId(CommitApi.GetCommitByProjectAndIdApiResponse apiResponse)
        {
            OnGetCommitByProjectAndId?.Invoke(this, new ApiResponseEventArgs(apiResponse));
        }

        internal void ExecuteOnErrorGetCommitByProjectAndId(Exception exception)
        {
            OnErrorGetCommitByProjectAndId?.Invoke(this, new ExceptionEventArgs(exception));
        }

        /// <summary>
        /// The event raised after the server response
        /// </summary>
        public event EventHandler<ApiResponseEventArgs>? OnGetCommitsByProject;

        /// <summary>
        /// The event raised after an error querying the server
        /// </summary>
        public event EventHandler<ExceptionEventArgs>? OnErrorGetCommitsByProject;

        internal void ExecuteOnGetCommitsByProject(CommitApi.GetCommitsByProjectApiResponse apiResponse)
        {
            OnGetCommitsByProject?.Invoke(this, new ApiResponseEventArgs(apiResponse));
        }

        internal void ExecuteOnErrorGetCommitsByProject(Exception exception)
        {
            OnErrorGetCommitsByProject?.Invoke(this, new ExceptionEventArgs(exception));
        }

        /// <summary>
        /// The event raised after the server response
        /// </summary>
        public event EventHandler<ApiResponseEventArgs>? OnPostCommitByProject;

        /// <summary>
        /// The event raised after an error querying the server
        /// </summary>
        public event EventHandler<ExceptionEventArgs>? OnErrorPostCommitByProject;

        internal void ExecuteOnPostCommitByProject(CommitApi.PostCommitByProjectApiResponse apiResponse)
        {
            OnPostCommitByProject?.Invoke(this, new ApiResponseEventArgs(apiResponse));
        }

        internal void ExecuteOnErrorPostCommitByProject(Exception exception)
        {
            OnErrorPostCommitByProject?.Invoke(this, new ExceptionEventArgs(exception));
        }
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public sealed partial class CommitApi : ICommitApi
    {
        private JsonSerializerOptions _jsonSerializerOptions;

        /// <summary>
        /// The logger factory
        /// </summary>
        public ILoggerFactory LoggerFactory { get; }

        /// <summary>
        /// The logger
        /// </summary>
        public ILogger<CommitApi> Logger { get; }

        /// <summary>
        /// The HttpClient
        /// </summary>
        public HttpClient HttpClient { get; }

        /// <summary>
        /// The class containing the events
        /// </summary>
        public CommitApiEvents Events { get; }

        /// <summary>
        /// Initializes a new instance of the <see cref="CommitApi"/> class.
        /// </summary>
        /// <returns></returns>
        public CommitApi(ILogger<CommitApi> logger, ILoggerFactory loggerFactory, HttpClient httpClient, JsonSerializerOptionsProvider jsonSerializerOptionsProvider, CommitApiEvents commitApiEvents)
        {
            _jsonSerializerOptions = jsonSerializerOptionsProvider.Options;
            LoggerFactory = loggerFactory;
            Logger = LoggerFactory.CreateLogger<CommitApi>();
            HttpClient = httpClient;
            Events = commitApiEvents;
        }

        partial void FormatGetCommitByProjectAndId(ref Guid projectId, ref Guid commitId);

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="projectId"></param>
        /// <param name="commitId"></param>
        private void AfterGetCommitByProjectAndIdDefaultImplementation(IGetCommitByProjectAndIdApiResponse apiResponseLocalVar, Guid projectId, Guid commitId)
        {
            bool suppressDefaultLog = false;
            AfterGetCommitByProjectAndId(ref suppressDefaultLog, apiResponseLocalVar, projectId, commitId);
            if (!suppressDefaultLog)
                Logger.LogInformation("{0,-9} | {1} | {3}", (apiResponseLocalVar.DownloadedAt - apiResponseLocalVar.RequestedAt).TotalSeconds, apiResponseLocalVar.StatusCode, apiResponseLocalVar.Path);
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="suppressDefaultLog"></param>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="projectId"></param>
        /// <param name="commitId"></param>
        partial void AfterGetCommitByProjectAndId(ref bool suppressDefaultLog, IGetCommitByProjectAndIdApiResponse apiResponseLocalVar, Guid projectId, Guid commitId);

        /// <summary>
        /// Logs exceptions that occur while retrieving the server response
        /// </summary>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="projectId"></param>
        /// <param name="commitId"></param>
        private void OnErrorGetCommitByProjectAndIdDefaultImplementation(Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, Guid projectId, Guid commitId)
        {
            bool suppressDefaultLogLocalVar = false;
            OnErrorGetCommitByProjectAndId(ref suppressDefaultLogLocalVar, exceptionLocalVar, pathFormatLocalVar, pathLocalVar, projectId, commitId);
            if (!suppressDefaultLogLocalVar)
                Logger.LogError(exceptionLocalVar, "An error occurred while sending the request to the server.");
        }

        /// <summary>
        /// A partial method that gives developers a way to provide customized exception handling
        /// </summary>
        /// <param name="suppressDefaultLogLocalVar"></param>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="projectId"></param>
        /// <param name="commitId"></param>
        partial void OnErrorGetCommitByProjectAndId(ref bool suppressDefaultLogLocalVar, Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, Guid projectId, Guid commitId);

        /// <summary>
        /// Get commit by project and ID 
        /// </summary>
        /// <param name="projectId">ID of the project</param>
        /// <param name="commitId">ID of the commit</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IGetCommitByProjectAndIdApiResponse"/>&gt;</returns>
        public async Task<IGetCommitByProjectAndIdApiResponse?> GetCommitByProjectAndIdOrDefaultAsync(Guid projectId, Guid commitId, System.Threading.CancellationToken cancellationToken = default)
        {
            try
            {
                return await GetCommitByProjectAndIdAsync(projectId, commitId, cancellationToken).ConfigureAwait(false);
            }
            catch (Exception)
            {
                return null;
            }
        }

        /// <summary>
        /// Get commit by project and ID 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">ID of the project</param>
        /// <param name="commitId">ID of the commit</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IGetCommitByProjectAndIdApiResponse"/>&gt;</returns>
        public async Task<IGetCommitByProjectAndIdApiResponse> GetCommitByProjectAndIdAsync(Guid projectId, Guid commitId, System.Threading.CancellationToken cancellationToken = default)
        {
            UriBuilder uriBuilderLocalVar = new UriBuilder();

            try
            {
                FormatGetCommitByProjectAndId(ref projectId, ref commitId);

                using (HttpRequestMessage httpRequestMessageLocalVar = new HttpRequestMessage())
                {
                    uriBuilderLocalVar.Host = HttpClient.BaseAddress!.Host;
                    uriBuilderLocalVar.Port = HttpClient.BaseAddress.Port;
                    uriBuilderLocalVar.Scheme = HttpClient.BaseAddress.Scheme;
                    uriBuilderLocalVar.Path = HttpClient.BaseAddress.AbsolutePath == "/"
                        ? "/projects/{projectId}/commits/{commitId}"
                        : string.Concat(HttpClient.BaseAddress.AbsolutePath, "/projects/{projectId}/commits/{commitId}");
                    uriBuilderLocalVar.Path = uriBuilderLocalVar.Path.Replace("%7BprojectId%7D", Uri.EscapeDataString(projectId.ToString()));
                    uriBuilderLocalVar.Path = uriBuilderLocalVar.Path.Replace("%7BcommitId%7D", Uri.EscapeDataString(commitId.ToString()));

                    httpRequestMessageLocalVar.RequestUri = uriBuilderLocalVar.Uri;

                    string[] acceptLocalVars = new string[] {
                        "application/json",
                        "application/ld+json"
                    };

                    string? acceptLocalVar = ClientUtils.SelectHeaderAccept(acceptLocalVars);

                    if (acceptLocalVar != null)
                        httpRequestMessageLocalVar.Headers.Accept.Add(new MediaTypeWithQualityHeaderValue(acceptLocalVar));

                    httpRequestMessageLocalVar.Method = HttpMethod.Get;

                    DateTime requestedAtLocalVar = DateTime.UtcNow;

                    using (HttpResponseMessage httpResponseMessageLocalVar = await HttpClient.SendAsync(httpRequestMessageLocalVar, cancellationToken).ConfigureAwait(false))
                    {
                        string responseContentLocalVar = await httpResponseMessageLocalVar.Content.ReadAsStringAsync(cancellationToken).ConfigureAwait(false);

                        ILogger<GetCommitByProjectAndIdApiResponse> apiResponseLoggerLocalVar = LoggerFactory.CreateLogger<GetCommitByProjectAndIdApiResponse>();

                        GetCommitByProjectAndIdApiResponse apiResponseLocalVar = new(apiResponseLoggerLocalVar, httpRequestMessageLocalVar, httpResponseMessageLocalVar, responseContentLocalVar, "/projects/{projectId}/commits/{commitId}", requestedAtLocalVar, _jsonSerializerOptions);

                        AfterGetCommitByProjectAndIdDefaultImplementation(apiResponseLocalVar, projectId, commitId);

                        Events.ExecuteOnGetCommitByProjectAndId(apiResponseLocalVar);

                        return apiResponseLocalVar;
                    }
                }
            }
            catch(Exception e)
            {
                OnErrorGetCommitByProjectAndIdDefaultImplementation(e, "/projects/{projectId}/commits/{commitId}", uriBuilderLocalVar.Path, projectId, commitId);
                Events.ExecuteOnErrorGetCommitByProjectAndId(e);
                throw;
            }
        }

        /// <summary>
        /// The <see cref="GetCommitByProjectAndIdApiResponse"/>
        /// </summary>
        public partial class GetCommitByProjectAndIdApiResponse : Org.OpenAPITools.Client.ApiResponse, IGetCommitByProjectAndIdApiResponse
        {
            /// <summary>
            /// The logger
            /// </summary>
            public ILogger<GetCommitByProjectAndIdApiResponse> Logger { get; }

            /// <summary>
            /// The <see cref="GetCommitByProjectAndIdApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="rawContent"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public GetCommitByProjectAndIdApiResponse(ILogger<GetCommitByProjectAndIdApiResponse> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, string rawContent, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, rawContent, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            partial void OnCreated(global::System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage);

            /// <summary>
            /// Returns true if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public bool IsOk => 200 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public Org.OpenAPITools.Model.Commit? Ok()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsOk
                    ? System.Text.Json.JsonSerializer.Deserialize<Org.OpenAPITools.Model.Commit>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 200 Ok and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryOk([NotNullWhen(true)]out Org.OpenAPITools.Model.Commit? result)
            {
                result = null;

                try
                {
                    result = Ok();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)200);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 404 NotFound
            /// </summary>
            /// <returns></returns>
            public bool IsNotFound => 404 == (int)StatusCode;

            /// <summary>
            /// Returns true if the response is 415 UnsupportedMediaType
            /// </summary>
            /// <returns></returns>
            public bool IsUnsupportedMediaType => 415 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 415 UnsupportedMediaType
            /// </summary>
            /// <returns></returns>
            public Org.OpenAPITools.Model.Error? UnsupportedMediaType()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsUnsupportedMediaType
                    ? System.Text.Json.JsonSerializer.Deserialize<Org.OpenAPITools.Model.Error>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 415 UnsupportedMediaType and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryUnsupportedMediaType([NotNullWhen(true)]out Org.OpenAPITools.Model.Error? result)
            {
                result = null;

                try
                {
                    result = UnsupportedMediaType();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)415);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 500 InternalServerError
            /// </summary>
            /// <returns></returns>
            public bool IsInternalServerError => 500 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 500 InternalServerError
            /// </summary>
            /// <returns></returns>
            public Org.OpenAPITools.Model.Error? InternalServerError()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsInternalServerError
                    ? System.Text.Json.JsonSerializer.Deserialize<Org.OpenAPITools.Model.Error>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 500 InternalServerError and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryInternalServerError([NotNullWhen(true)]out Org.OpenAPITools.Model.Error? result)
            {
                result = null;

                try
                {
                    result = InternalServerError();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)500);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is the default response type
            /// </summary>
            /// <returns></returns>
            public bool IsDefault => !IsOk && !IsNotFound && !IsUnsupportedMediaType && !IsInternalServerError;

            private void OnDeserializationErrorDefaultImplementation(Exception exception, HttpStatusCode httpStatusCode)
            {
                bool suppressDefaultLog = false;
                OnDeserializationError(ref suppressDefaultLog, exception, httpStatusCode);
                if (!suppressDefaultLog)
                    Logger.LogError(exception, "An error occurred while deserializing the {code} response.", httpStatusCode);
            }

            partial void OnDeserializationError(ref bool suppressDefaultLog, Exception exception, HttpStatusCode httpStatusCode);
        }

        partial void FormatGetCommitsByProject(ref Guid projectId, ref Option<string> pageAfter, ref Option<string> pageBefore, ref Option<int> pageSize);

        /// <summary>
        /// Validates the request parameters
        /// </summary>
        /// <param name="pageAfter"></param>
        /// <param name="pageBefore"></param>
        /// <returns></returns>
        private void ValidateGetCommitsByProject(Option<string> pageAfter, Option<string> pageBefore)
        {
            if (pageAfter.IsSet && pageAfter.Value == null)
                throw new ArgumentNullException(nameof(pageAfter));

            if (pageBefore.IsSet && pageBefore.Value == null)
                throw new ArgumentNullException(nameof(pageBefore));
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="projectId"></param>
        /// <param name="pageAfter"></param>
        /// <param name="pageBefore"></param>
        /// <param name="pageSize"></param>
        private void AfterGetCommitsByProjectDefaultImplementation(IGetCommitsByProjectApiResponse apiResponseLocalVar, Guid projectId, Option<string> pageAfter, Option<string> pageBefore, Option<int> pageSize)
        {
            bool suppressDefaultLog = false;
            AfterGetCommitsByProject(ref suppressDefaultLog, apiResponseLocalVar, projectId, pageAfter, pageBefore, pageSize);
            if (!suppressDefaultLog)
                Logger.LogInformation("{0,-9} | {1} | {3}", (apiResponseLocalVar.DownloadedAt - apiResponseLocalVar.RequestedAt).TotalSeconds, apiResponseLocalVar.StatusCode, apiResponseLocalVar.Path);
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="suppressDefaultLog"></param>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="projectId"></param>
        /// <param name="pageAfter"></param>
        /// <param name="pageBefore"></param>
        /// <param name="pageSize"></param>
        partial void AfterGetCommitsByProject(ref bool suppressDefaultLog, IGetCommitsByProjectApiResponse apiResponseLocalVar, Guid projectId, Option<string> pageAfter, Option<string> pageBefore, Option<int> pageSize);

        /// <summary>
        /// Logs exceptions that occur while retrieving the server response
        /// </summary>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="projectId"></param>
        /// <param name="pageAfter"></param>
        /// <param name="pageBefore"></param>
        /// <param name="pageSize"></param>
        private void OnErrorGetCommitsByProjectDefaultImplementation(Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, Guid projectId, Option<string> pageAfter, Option<string> pageBefore, Option<int> pageSize)
        {
            bool suppressDefaultLogLocalVar = false;
            OnErrorGetCommitsByProject(ref suppressDefaultLogLocalVar, exceptionLocalVar, pathFormatLocalVar, pathLocalVar, projectId, pageAfter, pageBefore, pageSize);
            if (!suppressDefaultLogLocalVar)
                Logger.LogError(exceptionLocalVar, "An error occurred while sending the request to the server.");
        }

        /// <summary>
        /// A partial method that gives developers a way to provide customized exception handling
        /// </summary>
        /// <param name="suppressDefaultLogLocalVar"></param>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="projectId"></param>
        /// <param name="pageAfter"></param>
        /// <param name="pageBefore"></param>
        /// <param name="pageSize"></param>
        partial void OnErrorGetCommitsByProject(ref bool suppressDefaultLogLocalVar, Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, Guid projectId, Option<string> pageAfter, Option<string> pageBefore, Option<int> pageSize);

        /// <summary>
        /// Get commits by project 
        /// </summary>
        /// <param name="projectId">ID of the project</param>
        /// <param name="pageAfter">Page after (optional)</param>
        /// <param name="pageBefore">Page before (optional)</param>
        /// <param name="pageSize">Page size (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IGetCommitsByProjectApiResponse"/>&gt;</returns>
        public async Task<IGetCommitsByProjectApiResponse?> GetCommitsByProjectOrDefaultAsync(Guid projectId, Option<string> pageAfter = default, Option<string> pageBefore = default, Option<int> pageSize = default, System.Threading.CancellationToken cancellationToken = default)
        {
            try
            {
                return await GetCommitsByProjectAsync(projectId, pageAfter, pageBefore, pageSize, cancellationToken).ConfigureAwait(false);
            }
            catch (Exception)
            {
                return null;
            }
        }

        /// <summary>
        /// Get commits by project 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">ID of the project</param>
        /// <param name="pageAfter">Page after (optional)</param>
        /// <param name="pageBefore">Page before (optional)</param>
        /// <param name="pageSize">Page size (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IGetCommitsByProjectApiResponse"/>&gt;</returns>
        public async Task<IGetCommitsByProjectApiResponse> GetCommitsByProjectAsync(Guid projectId, Option<string> pageAfter = default, Option<string> pageBefore = default, Option<int> pageSize = default, System.Threading.CancellationToken cancellationToken = default)
        {
            UriBuilder uriBuilderLocalVar = new UriBuilder();

            try
            {
                ValidateGetCommitsByProject(pageAfter, pageBefore);

                FormatGetCommitsByProject(ref projectId, ref pageAfter, ref pageBefore, ref pageSize);

                using (HttpRequestMessage httpRequestMessageLocalVar = new HttpRequestMessage())
                {
                    uriBuilderLocalVar.Host = HttpClient.BaseAddress!.Host;
                    uriBuilderLocalVar.Port = HttpClient.BaseAddress.Port;
                    uriBuilderLocalVar.Scheme = HttpClient.BaseAddress.Scheme;
                    uriBuilderLocalVar.Path = HttpClient.BaseAddress.AbsolutePath == "/"
                        ? "/projects/{projectId}/commits"
                        : string.Concat(HttpClient.BaseAddress.AbsolutePath, "/projects/{projectId}/commits");
                    uriBuilderLocalVar.Path = uriBuilderLocalVar.Path.Replace("%7BprojectId%7D", Uri.EscapeDataString(projectId.ToString()));

                    System.Collections.Specialized.NameValueCollection parseQueryStringLocalVar = System.Web.HttpUtility.ParseQueryString(string.Empty);

                    if (pageAfter.IsSet)
                        parseQueryStringLocalVar["page[after]"] = ClientUtils.ParameterToString(pageAfter.Value);

                    if (pageBefore.IsSet)
                        parseQueryStringLocalVar["page[before]"] = ClientUtils.ParameterToString(pageBefore.Value);

                    if (pageSize.IsSet)
                        parseQueryStringLocalVar["page[size]"] = ClientUtils.ParameterToString(pageSize.Value);

                    uriBuilderLocalVar.Query = parseQueryStringLocalVar.ToString();

                    httpRequestMessageLocalVar.RequestUri = uriBuilderLocalVar.Uri;

                    string[] acceptLocalVars = new string[] {
                        "application/json",
                        "application/ld+json"
                    };

                    string? acceptLocalVar = ClientUtils.SelectHeaderAccept(acceptLocalVars);

                    if (acceptLocalVar != null)
                        httpRequestMessageLocalVar.Headers.Accept.Add(new MediaTypeWithQualityHeaderValue(acceptLocalVar));

                    httpRequestMessageLocalVar.Method = HttpMethod.Get;

                    DateTime requestedAtLocalVar = DateTime.UtcNow;

                    using (HttpResponseMessage httpResponseMessageLocalVar = await HttpClient.SendAsync(httpRequestMessageLocalVar, cancellationToken).ConfigureAwait(false))
                    {
                        string responseContentLocalVar = await httpResponseMessageLocalVar.Content.ReadAsStringAsync(cancellationToken).ConfigureAwait(false);

                        ILogger<GetCommitsByProjectApiResponse> apiResponseLoggerLocalVar = LoggerFactory.CreateLogger<GetCommitsByProjectApiResponse>();

                        GetCommitsByProjectApiResponse apiResponseLocalVar = new(apiResponseLoggerLocalVar, httpRequestMessageLocalVar, httpResponseMessageLocalVar, responseContentLocalVar, "/projects/{projectId}/commits", requestedAtLocalVar, _jsonSerializerOptions);

                        AfterGetCommitsByProjectDefaultImplementation(apiResponseLocalVar, projectId, pageAfter, pageBefore, pageSize);

                        Events.ExecuteOnGetCommitsByProject(apiResponseLocalVar);

                        return apiResponseLocalVar;
                    }
                }
            }
            catch(Exception e)
            {
                OnErrorGetCommitsByProjectDefaultImplementation(e, "/projects/{projectId}/commits", uriBuilderLocalVar.Path, projectId, pageAfter, pageBefore, pageSize);
                Events.ExecuteOnErrorGetCommitsByProject(e);
                throw;
            }
        }

        /// <summary>
        /// The <see cref="GetCommitsByProjectApiResponse"/>
        /// </summary>
        public partial class GetCommitsByProjectApiResponse : Org.OpenAPITools.Client.ApiResponse, IGetCommitsByProjectApiResponse
        {
            /// <summary>
            /// The logger
            /// </summary>
            public ILogger<GetCommitsByProjectApiResponse> Logger { get; }

            /// <summary>
            /// The <see cref="GetCommitsByProjectApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="rawContent"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public GetCommitsByProjectApiResponse(ILogger<GetCommitsByProjectApiResponse> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, string rawContent, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, rawContent, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            partial void OnCreated(global::System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage);

            /// <summary>
            /// Returns true if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public bool IsOk => 200 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public List<Commit>? Ok()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsOk
                    ? System.Text.Json.JsonSerializer.Deserialize<List<Commit>>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 200 Ok and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryOk([NotNullWhen(true)]out List<Commit>? result)
            {
                result = null;

                try
                {
                    result = Ok();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)200);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 404 NotFound
            /// </summary>
            /// <returns></returns>
            public bool IsNotFound => 404 == (int)StatusCode;

            /// <summary>
            /// Returns true if the response is 415 UnsupportedMediaType
            /// </summary>
            /// <returns></returns>
            public bool IsUnsupportedMediaType => 415 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 415 UnsupportedMediaType
            /// </summary>
            /// <returns></returns>
            public Org.OpenAPITools.Model.Error? UnsupportedMediaType()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsUnsupportedMediaType
                    ? System.Text.Json.JsonSerializer.Deserialize<Org.OpenAPITools.Model.Error>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 415 UnsupportedMediaType and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryUnsupportedMediaType([NotNullWhen(true)]out Org.OpenAPITools.Model.Error? result)
            {
                result = null;

                try
                {
                    result = UnsupportedMediaType();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)415);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 500 InternalServerError
            /// </summary>
            /// <returns></returns>
            public bool IsInternalServerError => 500 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 500 InternalServerError
            /// </summary>
            /// <returns></returns>
            public Org.OpenAPITools.Model.Error? InternalServerError()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsInternalServerError
                    ? System.Text.Json.JsonSerializer.Deserialize<Org.OpenAPITools.Model.Error>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 500 InternalServerError and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryInternalServerError([NotNullWhen(true)]out Org.OpenAPITools.Model.Error? result)
            {
                result = null;

                try
                {
                    result = InternalServerError();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)500);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is the default response type
            /// </summary>
            /// <returns></returns>
            public bool IsDefault => !IsOk && !IsNotFound && !IsUnsupportedMediaType && !IsInternalServerError;

            private void OnDeserializationErrorDefaultImplementation(Exception exception, HttpStatusCode httpStatusCode)
            {
                bool suppressDefaultLog = false;
                OnDeserializationError(ref suppressDefaultLog, exception, httpStatusCode);
                if (!suppressDefaultLog)
                    Logger.LogError(exception, "An error occurred while deserializing the {code} response.", httpStatusCode);
            }

            partial void OnDeserializationError(ref bool suppressDefaultLog, Exception exception, HttpStatusCode httpStatusCode);
        }

        partial void FormatPostCommitByProject(ref Guid projectId, Commit body, ref Option<Guid> branchId);

        /// <summary>
        /// Validates the request parameters
        /// </summary>
        /// <param name="body"></param>
        /// <returns></returns>
        private void ValidatePostCommitByProject(Commit body)
        {
            if (body == null)
                throw new ArgumentNullException(nameof(body));
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="projectId"></param>
        /// <param name="body"></param>
        /// <param name="branchId"></param>
        private void AfterPostCommitByProjectDefaultImplementation(IPostCommitByProjectApiResponse apiResponseLocalVar, Guid projectId, Commit body, Option<Guid> branchId)
        {
            bool suppressDefaultLog = false;
            AfterPostCommitByProject(ref suppressDefaultLog, apiResponseLocalVar, projectId, body, branchId);
            if (!suppressDefaultLog)
                Logger.LogInformation("{0,-9} | {1} | {3}", (apiResponseLocalVar.DownloadedAt - apiResponseLocalVar.RequestedAt).TotalSeconds, apiResponseLocalVar.StatusCode, apiResponseLocalVar.Path);
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="suppressDefaultLog"></param>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="projectId"></param>
        /// <param name="body"></param>
        /// <param name="branchId"></param>
        partial void AfterPostCommitByProject(ref bool suppressDefaultLog, IPostCommitByProjectApiResponse apiResponseLocalVar, Guid projectId, Commit body, Option<Guid> branchId);

        /// <summary>
        /// Logs exceptions that occur while retrieving the server response
        /// </summary>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="projectId"></param>
        /// <param name="body"></param>
        /// <param name="branchId"></param>
        private void OnErrorPostCommitByProjectDefaultImplementation(Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, Guid projectId, Commit body, Option<Guid> branchId)
        {
            bool suppressDefaultLogLocalVar = false;
            OnErrorPostCommitByProject(ref suppressDefaultLogLocalVar, exceptionLocalVar, pathFormatLocalVar, pathLocalVar, projectId, body, branchId);
            if (!suppressDefaultLogLocalVar)
                Logger.LogError(exceptionLocalVar, "An error occurred while sending the request to the server.");
        }

        /// <summary>
        /// A partial method that gives developers a way to provide customized exception handling
        /// </summary>
        /// <param name="suppressDefaultLogLocalVar"></param>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="projectId"></param>
        /// <param name="body"></param>
        /// <param name="branchId"></param>
        partial void OnErrorPostCommitByProject(ref bool suppressDefaultLogLocalVar, Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, Guid projectId, Commit body, Option<Guid> branchId);

        /// <summary>
        /// Create commit by project 
        /// </summary>
        /// <param name="projectId">ID of the project</param>
        /// <param name="body"></param>
        /// <param name="branchId">ID of the branch - project&#39;s default branch if unspecified (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IPostCommitByProjectApiResponse"/>&gt;</returns>
        public async Task<IPostCommitByProjectApiResponse?> PostCommitByProjectOrDefaultAsync(Guid projectId, Commit body, Option<Guid> branchId = default, System.Threading.CancellationToken cancellationToken = default)
        {
            try
            {
                return await PostCommitByProjectAsync(projectId, body, branchId, cancellationToken).ConfigureAwait(false);
            }
            catch (Exception)
            {
                return null;
            }
        }

        /// <summary>
        /// Create commit by project 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">ID of the project</param>
        /// <param name="body"></param>
        /// <param name="branchId">ID of the branch - project&#39;s default branch if unspecified (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IPostCommitByProjectApiResponse"/>&gt;</returns>
        public async Task<IPostCommitByProjectApiResponse> PostCommitByProjectAsync(Guid projectId, Commit body, Option<Guid> branchId = default, System.Threading.CancellationToken cancellationToken = default)
        {
            UriBuilder uriBuilderLocalVar = new UriBuilder();

            try
            {
                ValidatePostCommitByProject(body);

                FormatPostCommitByProject(ref projectId, body, ref branchId);

                using (HttpRequestMessage httpRequestMessageLocalVar = new HttpRequestMessage())
                {
                    uriBuilderLocalVar.Host = HttpClient.BaseAddress!.Host;
                    uriBuilderLocalVar.Port = HttpClient.BaseAddress.Port;
                    uriBuilderLocalVar.Scheme = HttpClient.BaseAddress.Scheme;
                    uriBuilderLocalVar.Path = HttpClient.BaseAddress.AbsolutePath == "/"
                        ? "/projects/{projectId}/commits"
                        : string.Concat(HttpClient.BaseAddress.AbsolutePath, "/projects/{projectId}/commits");
                    uriBuilderLocalVar.Path = uriBuilderLocalVar.Path.Replace("%7BprojectId%7D", Uri.EscapeDataString(projectId.ToString()));

                    System.Collections.Specialized.NameValueCollection parseQueryStringLocalVar = System.Web.HttpUtility.ParseQueryString(string.Empty);

                    if (branchId.IsSet)
                        parseQueryStringLocalVar["branchId"] = ClientUtils.ParameterToString(branchId.Value);

                    uriBuilderLocalVar.Query = parseQueryStringLocalVar.ToString();

                    httpRequestMessageLocalVar.Content = (body as object) is System.IO.Stream stream
                        ? httpRequestMessageLocalVar.Content = new StreamContent(stream)
                        : httpRequestMessageLocalVar.Content = new StringContent(JsonSerializer.Serialize(body, _jsonSerializerOptions));

                    httpRequestMessageLocalVar.RequestUri = uriBuilderLocalVar.Uri;

                    string[] contentTypes = new string[] {
                        "application/json"
                    };

                    string? contentTypeLocalVar = ClientUtils.SelectHeaderContentType(contentTypes);

                    if (contentTypeLocalVar != null && httpRequestMessageLocalVar.Content != null)
                        httpRequestMessageLocalVar.Content.Headers.ContentType = new MediaTypeHeaderValue(contentTypeLocalVar);

                    string[] acceptLocalVars = new string[] {
                        "application/json",
                        "application/ld+json"
                    };

                    string? acceptLocalVar = ClientUtils.SelectHeaderAccept(acceptLocalVars);

                    if (acceptLocalVar != null)
                        httpRequestMessageLocalVar.Headers.Accept.Add(new MediaTypeWithQualityHeaderValue(acceptLocalVar));

                    httpRequestMessageLocalVar.Method = HttpMethod.Post;

                    DateTime requestedAtLocalVar = DateTime.UtcNow;

                    using (HttpResponseMessage httpResponseMessageLocalVar = await HttpClient.SendAsync(httpRequestMessageLocalVar, cancellationToken).ConfigureAwait(false))
                    {
                        string responseContentLocalVar = await httpResponseMessageLocalVar.Content.ReadAsStringAsync(cancellationToken).ConfigureAwait(false);

                        ILogger<PostCommitByProjectApiResponse> apiResponseLoggerLocalVar = LoggerFactory.CreateLogger<PostCommitByProjectApiResponse>();

                        PostCommitByProjectApiResponse apiResponseLocalVar = new(apiResponseLoggerLocalVar, httpRequestMessageLocalVar, httpResponseMessageLocalVar, responseContentLocalVar, "/projects/{projectId}/commits", requestedAtLocalVar, _jsonSerializerOptions);

                        AfterPostCommitByProjectDefaultImplementation(apiResponseLocalVar, projectId, body, branchId);

                        Events.ExecuteOnPostCommitByProject(apiResponseLocalVar);

                        return apiResponseLocalVar;
                    }
                }
            }
            catch(Exception e)
            {
                OnErrorPostCommitByProjectDefaultImplementation(e, "/projects/{projectId}/commits", uriBuilderLocalVar.Path, projectId, body, branchId);
                Events.ExecuteOnErrorPostCommitByProject(e);
                throw;
            }
        }

        /// <summary>
        /// The <see cref="PostCommitByProjectApiResponse"/>
        /// </summary>
        public partial class PostCommitByProjectApiResponse : Org.OpenAPITools.Client.ApiResponse, IPostCommitByProjectApiResponse
        {
            /// <summary>
            /// The logger
            /// </summary>
            public ILogger<PostCommitByProjectApiResponse> Logger { get; }

            /// <summary>
            /// The <see cref="PostCommitByProjectApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="rawContent"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public PostCommitByProjectApiResponse(ILogger<PostCommitByProjectApiResponse> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, string rawContent, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, rawContent, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            partial void OnCreated(global::System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage);

            /// <summary>
            /// Returns true if the response is 201 Created
            /// </summary>
            /// <returns></returns>
            public bool IsCreated => (201 == (int)StatusCode) || (200 == (int)StatusCode);

            /// <summary>
            /// Deserializes the response if the response is 201 Created
            /// </summary>
            /// <returns></returns>
            public Org.OpenAPITools.Model.Commit? Created()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsCreated
                    ? System.Text.Json.JsonSerializer.Deserialize<Org.OpenAPITools.Model.Commit>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 201 Created and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryCreated([NotNullWhen(true)]out Org.OpenAPITools.Model.Commit? result)
            {
                result = null;

                try
                {
                    result = Created();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)201);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 415 UnsupportedMediaType
            /// </summary>
            /// <returns></returns>
            public bool IsUnsupportedMediaType => 415 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 415 UnsupportedMediaType
            /// </summary>
            /// <returns></returns>
            public Org.OpenAPITools.Model.Error? UnsupportedMediaType()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsUnsupportedMediaType
                    ? System.Text.Json.JsonSerializer.Deserialize<Org.OpenAPITools.Model.Error>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 415 UnsupportedMediaType and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryUnsupportedMediaType([NotNullWhen(true)]out Org.OpenAPITools.Model.Error? result)
            {
                result = null;

                try
                {
                    result = UnsupportedMediaType();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)415);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 500 InternalServerError
            /// </summary>
            /// <returns></returns>
            public bool IsInternalServerError => 500 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 500 InternalServerError
            /// </summary>
            /// <returns></returns>
            public Org.OpenAPITools.Model.Error? InternalServerError()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsInternalServerError
                    ? System.Text.Json.JsonSerializer.Deserialize<Org.OpenAPITools.Model.Error>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 500 InternalServerError and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryInternalServerError([NotNullWhen(true)]out Org.OpenAPITools.Model.Error? result)
            {
                result = null;

                try
                {
                    result = InternalServerError();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)500);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is the default response type
            /// </summary>
            /// <returns></returns>
            public bool IsDefault => !IsCreated && !IsUnsupportedMediaType && !IsInternalServerError;

            private void OnDeserializationErrorDefaultImplementation(Exception exception, HttpStatusCode httpStatusCode)
            {
                bool suppressDefaultLog = false;
                OnDeserializationError(ref suppressDefaultLog, exception, httpStatusCode);
                if (!suppressDefaultLog)
                    Logger.LogError(exception, "An error occurred while deserializing the {code} response.", httpStatusCode);
            }

            partial void OnDeserializationError(ref bool suppressDefaultLog, Exception exception, HttpStatusCode httpStatusCode);
        }
    }
}
