// <auto-generated>
/*
 * SysML v2 API and Services
 *
 * REST/HTTP binding (PSM) for the SysML v2 standard API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections.Generic;
using System.Net;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text.Json;
using Org.OpenAPITools.Client;
using Org.OpenAPITools.Model;
using System.Diagnostics.CodeAnalysis;

namespace Org.OpenAPITools.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// This class is registered as transient.
    /// </summary>
    public interface IRelationshipApi : IApi
    {
        /// <summary>
        /// The class containing the events
        /// </summary>
        RelationshipApiEvents Events { get; }

        /// <summary>
        /// Get relationships by project, commit, and related element
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">ID of the project</param>
        /// <param name="commitId">ID of the commit</param>
        /// <param name="relatedElementId">ID of the related element</param>
        /// <param name="direction">Filter for relationships that are incoming (in), outgoing (out), or both relative to the related element (optional, default to both)</param>
        /// <param name="pageAfter">Page after (optional)</param>
        /// <param name="pageBefore">Page before (optional)</param>
        /// <param name="pageSize">Page size (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IGetRelationshipsByProjectCommitRelatedElementApiResponse"/>&gt;</returns>
        Task<IGetRelationshipsByProjectCommitRelatedElementApiResponse> GetRelationshipsByProjectCommitRelatedElementAsync(Guid projectId, Guid commitId, Guid relatedElementId, Option<string> direction = default, Option<string> pageAfter = default, Option<string> pageBefore = default, Option<int> pageSize = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Get relationships by project, commit, and related element
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <param name="projectId">ID of the project</param>
        /// <param name="commitId">ID of the commit</param>
        /// <param name="relatedElementId">ID of the related element</param>
        /// <param name="direction">Filter for relationships that are incoming (in), outgoing (out), or both relative to the related element (optional, default to both)</param>
        /// <param name="pageAfter">Page after (optional)</param>
        /// <param name="pageBefore">Page before (optional)</param>
        /// <param name="pageSize">Page size (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IGetRelationshipsByProjectCommitRelatedElementApiResponse"/>?&gt;</returns>
        Task<IGetRelationshipsByProjectCommitRelatedElementApiResponse?> GetRelationshipsByProjectCommitRelatedElementOrDefaultAsync(Guid projectId, Guid commitId, Guid relatedElementId, Option<string> direction = default, Option<string> pageAfter = default, Option<string> pageBefore = default, Option<int> pageSize = default, System.Threading.CancellationToken cancellationToken = default);
    }

    /// <summary>
    /// The <see cref="IGetRelationshipsByProjectCommitRelatedElementApiResponse"/>
    /// </summary>
    public interface IGetRelationshipsByProjectCommitRelatedElementApiResponse : Org.OpenAPITools.Client.IApiResponse, IOk<List<Relationship>?>, IUnsupportedMediaType<Org.OpenAPITools.Model.Error?>, IInternalServerError<Org.OpenAPITools.Model.Error?>
    {
        /// <summary>
        /// Returns true if the response is 200 Ok
        /// </summary>
        /// <returns></returns>
        bool IsOk { get; }

        /// <summary>
        /// Returns true if the response is 415 UnsupportedMediaType
        /// </summary>
        /// <returns></returns>
        bool IsUnsupportedMediaType { get; }

        /// <summary>
        /// Returns true if the response is 500 InternalServerError
        /// </summary>
        /// <returns></returns>
        bool IsInternalServerError { get; }

        /// <summary>
        /// Returns true if the response is the default response type
        /// </summary>
        /// <returns></returns>
        bool IsDefault { get; }
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public class RelationshipApiEvents
    {
        /// <summary>
        /// The event raised after the server response
        /// </summary>
        public event EventHandler<ApiResponseEventArgs>? OnGetRelationshipsByProjectCommitRelatedElement;

        /// <summary>
        /// The event raised after an error querying the server
        /// </summary>
        public event EventHandler<ExceptionEventArgs>? OnErrorGetRelationshipsByProjectCommitRelatedElement;

        internal void ExecuteOnGetRelationshipsByProjectCommitRelatedElement(RelationshipApi.GetRelationshipsByProjectCommitRelatedElementApiResponse apiResponse)
        {
            OnGetRelationshipsByProjectCommitRelatedElement?.Invoke(this, new ApiResponseEventArgs(apiResponse));
        }

        internal void ExecuteOnErrorGetRelationshipsByProjectCommitRelatedElement(Exception exception)
        {
            OnErrorGetRelationshipsByProjectCommitRelatedElement?.Invoke(this, new ExceptionEventArgs(exception));
        }
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public sealed partial class RelationshipApi : IRelationshipApi
    {
        private JsonSerializerOptions _jsonSerializerOptions;

        /// <summary>
        /// The logger factory
        /// </summary>
        public ILoggerFactory LoggerFactory { get; }

        /// <summary>
        /// The logger
        /// </summary>
        public ILogger<RelationshipApi> Logger { get; }

        /// <summary>
        /// The HttpClient
        /// </summary>
        public HttpClient HttpClient { get; }

        /// <summary>
        /// The class containing the events
        /// </summary>
        public RelationshipApiEvents Events { get; }

        /// <summary>
        /// Initializes a new instance of the <see cref="RelationshipApi"/> class.
        /// </summary>
        /// <returns></returns>
        public RelationshipApi(ILogger<RelationshipApi> logger, ILoggerFactory loggerFactory, HttpClient httpClient, JsonSerializerOptionsProvider jsonSerializerOptionsProvider, RelationshipApiEvents relationshipApiEvents)
        {
            _jsonSerializerOptions = jsonSerializerOptionsProvider.Options;
            LoggerFactory = loggerFactory;
            Logger = LoggerFactory.CreateLogger<RelationshipApi>();
            HttpClient = httpClient;
            Events = relationshipApiEvents;
        }

        partial void FormatGetRelationshipsByProjectCommitRelatedElement(ref Guid projectId, ref Guid commitId, ref Guid relatedElementId, ref Option<string> direction, ref Option<string> pageAfter, ref Option<string> pageBefore, ref Option<int> pageSize);

        /// <summary>
        /// Validates the request parameters
        /// </summary>
        /// <param name="direction"></param>
        /// <param name="pageAfter"></param>
        /// <param name="pageBefore"></param>
        /// <returns></returns>
        private void ValidateGetRelationshipsByProjectCommitRelatedElement(Option<string> direction, Option<string> pageAfter, Option<string> pageBefore)
        {
            if (direction.IsSet && direction.Value == null)
                throw new ArgumentNullException(nameof(direction));

            if (pageAfter.IsSet && pageAfter.Value == null)
                throw new ArgumentNullException(nameof(pageAfter));

            if (pageBefore.IsSet && pageBefore.Value == null)
                throw new ArgumentNullException(nameof(pageBefore));
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="projectId"></param>
        /// <param name="commitId"></param>
        /// <param name="relatedElementId"></param>
        /// <param name="direction"></param>
        /// <param name="pageAfter"></param>
        /// <param name="pageBefore"></param>
        /// <param name="pageSize"></param>
        private void AfterGetRelationshipsByProjectCommitRelatedElementDefaultImplementation(IGetRelationshipsByProjectCommitRelatedElementApiResponse apiResponseLocalVar, Guid projectId, Guid commitId, Guid relatedElementId, Option<string> direction, Option<string> pageAfter, Option<string> pageBefore, Option<int> pageSize)
        {
            bool suppressDefaultLog = false;
            AfterGetRelationshipsByProjectCommitRelatedElement(ref suppressDefaultLog, apiResponseLocalVar, projectId, commitId, relatedElementId, direction, pageAfter, pageBefore, pageSize);
            if (!suppressDefaultLog)
                Logger.LogInformation("{0,-9} | {1} | {3}", (apiResponseLocalVar.DownloadedAt - apiResponseLocalVar.RequestedAt).TotalSeconds, apiResponseLocalVar.StatusCode, apiResponseLocalVar.Path);
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="suppressDefaultLog"></param>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="projectId"></param>
        /// <param name="commitId"></param>
        /// <param name="relatedElementId"></param>
        /// <param name="direction"></param>
        /// <param name="pageAfter"></param>
        /// <param name="pageBefore"></param>
        /// <param name="pageSize"></param>
        partial void AfterGetRelationshipsByProjectCommitRelatedElement(ref bool suppressDefaultLog, IGetRelationshipsByProjectCommitRelatedElementApiResponse apiResponseLocalVar, Guid projectId, Guid commitId, Guid relatedElementId, Option<string> direction, Option<string> pageAfter, Option<string> pageBefore, Option<int> pageSize);

        /// <summary>
        /// Logs exceptions that occur while retrieving the server response
        /// </summary>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="projectId"></param>
        /// <param name="commitId"></param>
        /// <param name="relatedElementId"></param>
        /// <param name="direction"></param>
        /// <param name="pageAfter"></param>
        /// <param name="pageBefore"></param>
        /// <param name="pageSize"></param>
        private void OnErrorGetRelationshipsByProjectCommitRelatedElementDefaultImplementation(Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, Guid projectId, Guid commitId, Guid relatedElementId, Option<string> direction, Option<string> pageAfter, Option<string> pageBefore, Option<int> pageSize)
        {
            bool suppressDefaultLogLocalVar = false;
            OnErrorGetRelationshipsByProjectCommitRelatedElement(ref suppressDefaultLogLocalVar, exceptionLocalVar, pathFormatLocalVar, pathLocalVar, projectId, commitId, relatedElementId, direction, pageAfter, pageBefore, pageSize);
            if (!suppressDefaultLogLocalVar)
                Logger.LogError(exceptionLocalVar, "An error occurred while sending the request to the server.");
        }

        /// <summary>
        /// A partial method that gives developers a way to provide customized exception handling
        /// </summary>
        /// <param name="suppressDefaultLogLocalVar"></param>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="projectId"></param>
        /// <param name="commitId"></param>
        /// <param name="relatedElementId"></param>
        /// <param name="direction"></param>
        /// <param name="pageAfter"></param>
        /// <param name="pageBefore"></param>
        /// <param name="pageSize"></param>
        partial void OnErrorGetRelationshipsByProjectCommitRelatedElement(ref bool suppressDefaultLogLocalVar, Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, Guid projectId, Guid commitId, Guid relatedElementId, Option<string> direction, Option<string> pageAfter, Option<string> pageBefore, Option<int> pageSize);

        /// <summary>
        /// Get relationships by project, commit, and related element 
        /// </summary>
        /// <param name="projectId">ID of the project</param>
        /// <param name="commitId">ID of the commit</param>
        /// <param name="relatedElementId">ID of the related element</param>
        /// <param name="direction">Filter for relationships that are incoming (in), outgoing (out), or both relative to the related element (optional, default to both)</param>
        /// <param name="pageAfter">Page after (optional)</param>
        /// <param name="pageBefore">Page before (optional)</param>
        /// <param name="pageSize">Page size (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IGetRelationshipsByProjectCommitRelatedElementApiResponse"/>&gt;</returns>
        public async Task<IGetRelationshipsByProjectCommitRelatedElementApiResponse?> GetRelationshipsByProjectCommitRelatedElementOrDefaultAsync(Guid projectId, Guid commitId, Guid relatedElementId, Option<string> direction = default, Option<string> pageAfter = default, Option<string> pageBefore = default, Option<int> pageSize = default, System.Threading.CancellationToken cancellationToken = default)
        {
            try
            {
                return await GetRelationshipsByProjectCommitRelatedElementAsync(projectId, commitId, relatedElementId, direction, pageAfter, pageBefore, pageSize, cancellationToken).ConfigureAwait(false);
            }
            catch (Exception)
            {
                return null;
            }
        }

        /// <summary>
        /// Get relationships by project, commit, and related element 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">ID of the project</param>
        /// <param name="commitId">ID of the commit</param>
        /// <param name="relatedElementId">ID of the related element</param>
        /// <param name="direction">Filter for relationships that are incoming (in), outgoing (out), or both relative to the related element (optional, default to both)</param>
        /// <param name="pageAfter">Page after (optional)</param>
        /// <param name="pageBefore">Page before (optional)</param>
        /// <param name="pageSize">Page size (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IGetRelationshipsByProjectCommitRelatedElementApiResponse"/>&gt;</returns>
        public async Task<IGetRelationshipsByProjectCommitRelatedElementApiResponse> GetRelationshipsByProjectCommitRelatedElementAsync(Guid projectId, Guid commitId, Guid relatedElementId, Option<string> direction = default, Option<string> pageAfter = default, Option<string> pageBefore = default, Option<int> pageSize = default, System.Threading.CancellationToken cancellationToken = default)
        {
            UriBuilder uriBuilderLocalVar = new UriBuilder();

            try
            {
                ValidateGetRelationshipsByProjectCommitRelatedElement(direction, pageAfter, pageBefore);

                FormatGetRelationshipsByProjectCommitRelatedElement(ref projectId, ref commitId, ref relatedElementId, ref direction, ref pageAfter, ref pageBefore, ref pageSize);

                using (HttpRequestMessage httpRequestMessageLocalVar = new HttpRequestMessage())
                {
                    uriBuilderLocalVar.Host = HttpClient.BaseAddress!.Host;
                    uriBuilderLocalVar.Port = HttpClient.BaseAddress.Port;
                    uriBuilderLocalVar.Scheme = HttpClient.BaseAddress.Scheme;
                    uriBuilderLocalVar.Path = HttpClient.BaseAddress.AbsolutePath == "/"
                        ? "/projects/{projectId}/commits/{commitId}/elements/{relatedElementId}/relationships"
                        : string.Concat(HttpClient.BaseAddress.AbsolutePath, "/projects/{projectId}/commits/{commitId}/elements/{relatedElementId}/relationships");
                    uriBuilderLocalVar.Path = uriBuilderLocalVar.Path.Replace("%7BprojectId%7D", Uri.EscapeDataString(projectId.ToString()));
                    uriBuilderLocalVar.Path = uriBuilderLocalVar.Path.Replace("%7BcommitId%7D", Uri.EscapeDataString(commitId.ToString()));
                    uriBuilderLocalVar.Path = uriBuilderLocalVar.Path.Replace("%7BrelatedElementId%7D", Uri.EscapeDataString(relatedElementId.ToString()));

                    System.Collections.Specialized.NameValueCollection parseQueryStringLocalVar = System.Web.HttpUtility.ParseQueryString(string.Empty);

                    if (direction.IsSet)
                        parseQueryStringLocalVar["direction"] = ClientUtils.ParameterToString(direction.Value);

                    if (pageAfter.IsSet)
                        parseQueryStringLocalVar["page[after]"] = ClientUtils.ParameterToString(pageAfter.Value);

                    if (pageBefore.IsSet)
                        parseQueryStringLocalVar["page[before]"] = ClientUtils.ParameterToString(pageBefore.Value);

                    if (pageSize.IsSet)
                        parseQueryStringLocalVar["page[size]"] = ClientUtils.ParameterToString(pageSize.Value);

                    uriBuilderLocalVar.Query = parseQueryStringLocalVar.ToString();

                    httpRequestMessageLocalVar.RequestUri = uriBuilderLocalVar.Uri;

                    string[] acceptLocalVars = new string[] {
                        "application/json",
                        "application/ld+json"
                    };

                    string? acceptLocalVar = ClientUtils.SelectHeaderAccept(acceptLocalVars);

                    if (acceptLocalVar != null)
                        httpRequestMessageLocalVar.Headers.Accept.Add(new MediaTypeWithQualityHeaderValue(acceptLocalVar));

                    httpRequestMessageLocalVar.Method = HttpMethod.Get;

                    DateTime requestedAtLocalVar = DateTime.UtcNow;

                    using (HttpResponseMessage httpResponseMessageLocalVar = await HttpClient.SendAsync(httpRequestMessageLocalVar, cancellationToken).ConfigureAwait(false))
                    {
                        string responseContentLocalVar = await httpResponseMessageLocalVar.Content.ReadAsStringAsync(cancellationToken).ConfigureAwait(false);

                        ILogger<GetRelationshipsByProjectCommitRelatedElementApiResponse> apiResponseLoggerLocalVar = LoggerFactory.CreateLogger<GetRelationshipsByProjectCommitRelatedElementApiResponse>();

                        GetRelationshipsByProjectCommitRelatedElementApiResponse apiResponseLocalVar = new(apiResponseLoggerLocalVar, httpRequestMessageLocalVar, httpResponseMessageLocalVar, responseContentLocalVar, "/projects/{projectId}/commits/{commitId}/elements/{relatedElementId}/relationships", requestedAtLocalVar, _jsonSerializerOptions);

                        AfterGetRelationshipsByProjectCommitRelatedElementDefaultImplementation(apiResponseLocalVar, projectId, commitId, relatedElementId, direction, pageAfter, pageBefore, pageSize);

                        Events.ExecuteOnGetRelationshipsByProjectCommitRelatedElement(apiResponseLocalVar);

                        return apiResponseLocalVar;
                    }
                }
            }
            catch(Exception e)
            {
                OnErrorGetRelationshipsByProjectCommitRelatedElementDefaultImplementation(e, "/projects/{projectId}/commits/{commitId}/elements/{relatedElementId}/relationships", uriBuilderLocalVar.Path, projectId, commitId, relatedElementId, direction, pageAfter, pageBefore, pageSize);
                Events.ExecuteOnErrorGetRelationshipsByProjectCommitRelatedElement(e);
                throw;
            }
        }

        /// <summary>
        /// The <see cref="GetRelationshipsByProjectCommitRelatedElementApiResponse"/>
        /// </summary>
        public partial class GetRelationshipsByProjectCommitRelatedElementApiResponse : Org.OpenAPITools.Client.ApiResponse, IGetRelationshipsByProjectCommitRelatedElementApiResponse
        {
            /// <summary>
            /// The logger
            /// </summary>
            public ILogger<GetRelationshipsByProjectCommitRelatedElementApiResponse> Logger { get; }

            /// <summary>
            /// The <see cref="GetRelationshipsByProjectCommitRelatedElementApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="rawContent"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public GetRelationshipsByProjectCommitRelatedElementApiResponse(ILogger<GetRelationshipsByProjectCommitRelatedElementApiResponse> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, string rawContent, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, rawContent, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            partial void OnCreated(global::System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage);

            /// <summary>
            /// Returns true if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public bool IsOk => 200 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public List<Relationship>? Ok()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsOk
                    ? System.Text.Json.JsonSerializer.Deserialize<List<Relationship>>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 200 Ok and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryOk([NotNullWhen(true)]out List<Relationship>? result)
            {
                result = null;

                try
                {
                    result = Ok();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)200);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 415 UnsupportedMediaType
            /// </summary>
            /// <returns></returns>
            public bool IsUnsupportedMediaType => 415 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 415 UnsupportedMediaType
            /// </summary>
            /// <returns></returns>
            public Org.OpenAPITools.Model.Error? UnsupportedMediaType()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsUnsupportedMediaType
                    ? System.Text.Json.JsonSerializer.Deserialize<Org.OpenAPITools.Model.Error>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 415 UnsupportedMediaType and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryUnsupportedMediaType([NotNullWhen(true)]out Org.OpenAPITools.Model.Error? result)
            {
                result = null;

                try
                {
                    result = UnsupportedMediaType();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)415);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 500 InternalServerError
            /// </summary>
            /// <returns></returns>
            public bool IsInternalServerError => 500 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 500 InternalServerError
            /// </summary>
            /// <returns></returns>
            public Org.OpenAPITools.Model.Error? InternalServerError()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsInternalServerError
                    ? System.Text.Json.JsonSerializer.Deserialize<Org.OpenAPITools.Model.Error>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 500 InternalServerError and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryInternalServerError([NotNullWhen(true)]out Org.OpenAPITools.Model.Error? result)
            {
                result = null;

                try
                {
                    result = InternalServerError();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)500);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is the default response type
            /// </summary>
            /// <returns></returns>
            public bool IsDefault => !IsOk && !IsUnsupportedMediaType && !IsInternalServerError;

            private void OnDeserializationErrorDefaultImplementation(Exception exception, HttpStatusCode httpStatusCode)
            {
                bool suppressDefaultLog = false;
                OnDeserializationError(ref suppressDefaultLog, exception, httpStatusCode);
                if (!suppressDefaultLog)
                    Logger.LogError(exception, "An error occurred while deserializing the {code} response.", httpStatusCode);
            }

            partial void OnDeserializationError(ref bool suppressDefaultLog, Exception exception, HttpStatusCode httpStatusCode);
        }
    }
}
