/*
 * SysML v2 API and Services
 *
 * REST/HTTP binding (PSM) for the SysML v2 standard API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing Branch
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BranchTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Branch
        //private Branch instance;

        public BranchTests()
        {
            // TODO uncomment below to create an instance of Branch
            //instance = new Branch();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Branch
        /// </summary>
        [Fact]
        public void BranchInstanceTest()
        {
            // TODO uncomment below to test "IsType" Branch
            //Assert.IsType<Branch>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'Head'
        /// </summary>
        [Fact]
        public void HeadTest()
        {
            // TODO unit test for the property 'Head'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'OwningProject'
        /// </summary>
        [Fact]
        public void OwningProjectTest()
        {
            // TODO unit test for the property 'OwningProject'
        }

        /// <summary>
        /// Test the property 'ReferencedCommit'
        /// </summary>
        [Fact]
        public void ReferencedCommitTest()
        {
            // TODO unit test for the property 'ReferencedCommit'
        }

        /// <summary>
        /// Test the property 'Timestamp'
        /// </summary>
        [Fact]
        public void TimestampTest()
        {
            // TODO unit test for the property 'Timestamp'
        }
    }
}
