/*
 * SysML v2 API and Services
 *
 * REST/HTTP binding (PSM) for the SysML v2 standard API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing Commit
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CommitTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Commit
        //private Commit instance;

        public CommitTests()
        {
            // TODO uncomment below to create an instance of Commit
            //instance = new Commit();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Commit
        /// </summary>
        [Fact]
        public void CommitInstanceTest()
        {
            // TODO uncomment below to test "IsType" Commit
            //Assert.IsType<Commit>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'Change'
        /// </summary>
        [Fact]
        public void ChangeTest()
        {
            // TODO unit test for the property 'Change'
        }

        /// <summary>
        /// Test the property 'OwningProject'
        /// </summary>
        [Fact]
        public void OwningProjectTest()
        {
            // TODO unit test for the property 'OwningProject'
        }

        /// <summary>
        /// Test the property 'PreviousCommit'
        /// </summary>
        [Fact]
        public void PreviousCommitTest()
        {
            // TODO unit test for the property 'PreviousCommit'
        }
    }
}
