/*
 * SysML v2 API and Services
 *
 * REST/HTTP binding (PSM) for the SysML v2 standard API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing CompositeConstraint
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CompositeConstraintTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CompositeConstraint
        //private CompositeConstraint instance;

        public CompositeConstraintTests()
        {
            // TODO uncomment below to create an instance of CompositeConstraint
            //instance = new CompositeConstraint();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CompositeConstraint
        /// </summary>
        [Fact]
        public void CompositeConstraintInstanceTest()
        {
            // TODO uncomment below to test "IsType" CompositeConstraint
            //Assert.IsType<CompositeConstraint>(instance);
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'Constraint'
        /// </summary>
        [Fact]
        public void ConstraintTest()
        {
            // TODO unit test for the property 'Constraint'
        }

        /// <summary>
        /// Test the property 'Operator'
        /// </summary>
        [Fact]
        public void OperatorTest()
        {
            // TODO unit test for the property 'Operator'
        }
    }
}
