/*
 * SysML v2 API and Services
 *
 * REST/HTTP binding (PSM) for the SysML v2 standard API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing Tag
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TagTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Tag
        //private Tag instance;

        public TagTests()
        {
            // TODO uncomment below to create an instance of Tag
            //instance = new Tag();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Tag
        /// </summary>
        [Fact]
        public void TagInstanceTest()
        {
            // TODO uncomment below to test "IsType" Tag
            //Assert.IsType<Tag>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'OwningProject'
        /// </summary>
        [Fact]
        public void OwningProjectTest()
        {
            // TODO unit test for the property 'OwningProject'
        }

        /// <summary>
        /// Test the property 'ReferencedCommit'
        /// </summary>
        [Fact]
        public void ReferencedCommitTest()
        {
            // TODO unit test for the property 'ReferencedCommit'
        }

        /// <summary>
        /// Test the property 'TaggedCommit'
        /// </summary>
        [Fact]
        public void TaggedCommitTest()
        {
            // TODO unit test for the property 'TaggedCommit'
        }

        /// <summary>
        /// Test the property 'Timestamp'
        /// </summary>
        [Fact]
        public void TimestampTest()
        {
            // TODO unit test for the property 'Timestamp'
        }
    }
}
