// <auto-generated>
/*
 * SysML v2 API and Services
 *
 * REST/HTTP binding (PSM) for the SysML v2 standard API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Branch
    /// </summary>
    public partial class Branch : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Branch" /> class.
        /// </summary>
        /// <param name="id">id</param>
        /// <param name="type">type</param>
        /// <param name="alias">alias</param>
        /// <param name="created">created</param>
        /// <param name="deleted">deleted</param>
        /// <param name="description">description</param>
        /// <param name="head">head</param>
        /// <param name="name">name</param>
        /// <param name="owningProject">owningProject</param>
        /// <param name="referencedCommit">referencedCommit</param>
        /// <param name="timestamp">timestamp</param>
        [JsonConstructor]
        public Branch(Option<Guid?> id = default, Option<TypeEnum?> type = default, Option<List<string>?> alias = default, Option<string?> created = default, Option<string?> deleted = default, Option<string?> description = default, Option<BranchHead?> head = default, Option<string?> name = default, Option<BranchOwningProject?> owningProject = default, Option<BranchHead?> referencedCommit = default, Option<DateTime?> timestamp = default)
        {
            IdOption = id;
            TypeOption = type;
            AliasOption = alias;
            CreatedOption = created;
            DeletedOption = deleted;
            DescriptionOption = description;
            HeadOption = head;
            NameOption = name;
            OwningProjectOption = owningProject;
            ReferencedCommitOption = referencedCommit;
            TimestampOption = timestamp;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Defines Type
        /// </summary>
        public enum TypeEnum
        {
            /// <summary>
            /// Enum Branch for value: Branch
            /// </summary>
            Branch = 1
        }

        /// <summary>
        /// Returns a <see cref="TypeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static TypeEnum TypeEnumFromString(string value)
        {
            if (value.Equals("Branch"))
                return TypeEnum.Branch;

            throw new NotImplementedException($"Could not convert value to type TypeEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="TypeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static TypeEnum? TypeEnumFromStringOrDefault(string value)
        {
            if (value.Equals("Branch"))
                return TypeEnum.Branch;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="TypeEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string TypeEnumToJsonValue(TypeEnum? value)
        {
            if (value == TypeEnum.Branch)
                return "Branch";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Used to track the state of Type
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<TypeEnum?> TypeOption { get; private set; }

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [JsonPropertyName("@type")]
        public TypeEnum? Type { get { return this.TypeOption; } set { this.TypeOption = new(value); } }

        /// <summary>
        /// Used to track the state of Id
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Guid?> IdOption { get; private set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("@id")]
        public Guid? Id { get { return this.IdOption; } set { this.IdOption = new(value); } }

        /// <summary>
        /// Used to track the state of Alias
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<string>?> AliasOption { get; private set; }

        /// <summary>
        /// Gets or Sets Alias
        /// </summary>
        [JsonPropertyName("alias")]
        public List<string>? Alias { get { return this.AliasOption; } set { this.AliasOption = new(value); } }

        /// <summary>
        /// Used to track the state of Created
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> CreatedOption { get; private set; }

        /// <summary>
        /// Gets or Sets Created
        /// </summary>
        [JsonPropertyName("created")]
        public string? Created { get { return this.CreatedOption; } set { this.CreatedOption = new(value); } }

        /// <summary>
        /// Used to track the state of Deleted
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> DeletedOption { get; private set; }

        /// <summary>
        /// Gets or Sets Deleted
        /// </summary>
        [JsonPropertyName("deleted")]
        public string? Deleted { get { return this.DeletedOption; } set { this.DeletedOption = new(value); } }

        /// <summary>
        /// Used to track the state of Description
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> DescriptionOption { get; private set; }

        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        [JsonPropertyName("description")]
        public string? Description { get { return this.DescriptionOption; } set { this.DescriptionOption = new(value); } }

        /// <summary>
        /// Used to track the state of Head
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<BranchHead?> HeadOption { get; private set; }

        /// <summary>
        /// Gets or Sets Head
        /// </summary>
        [JsonPropertyName("head")]
        public BranchHead? Head { get { return this.HeadOption; } set { this.HeadOption = new(value); } }

        /// <summary>
        /// Used to track the state of Name
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> NameOption { get; private set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [JsonPropertyName("name")]
        public string? Name { get { return this.NameOption; } set { this.NameOption = new(value); } }

        /// <summary>
        /// Used to track the state of OwningProject
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<BranchOwningProject?> OwningProjectOption { get; private set; }

        /// <summary>
        /// Gets or Sets OwningProject
        /// </summary>
        [JsonPropertyName("owningProject")]
        public BranchOwningProject? OwningProject { get { return this.OwningProjectOption; } set { this.OwningProjectOption = new(value); } }

        /// <summary>
        /// Used to track the state of ReferencedCommit
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<BranchHead?> ReferencedCommitOption { get; private set; }

        /// <summary>
        /// Gets or Sets ReferencedCommit
        /// </summary>
        [JsonPropertyName("referencedCommit")]
        public BranchHead? ReferencedCommit { get { return this.ReferencedCommitOption; } set { this.ReferencedCommitOption = new(value); } }

        /// <summary>
        /// Used to track the state of Timestamp
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTime?> TimestampOption { get; private set; }

        /// <summary>
        /// Gets or Sets Timestamp
        /// </summary>
        [JsonPropertyName("timestamp")]
        public DateTime? Timestamp { get { return this.TimestampOption; } set { this.TimestampOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Branch {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Alias: ").Append(Alias).Append("\n");
            sb.Append("  Created: ").Append(Created).Append("\n");
            sb.Append("  Deleted: ").Append(Deleted).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  Head: ").Append(Head).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  OwningProject: ").Append(OwningProject).Append("\n");
            sb.Append("  ReferencedCommit: ").Append(ReferencedCommit).Append("\n");
            sb.Append("  Timestamp: ").Append(Timestamp).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="Branch" />
    /// </summary>
    public class BranchJsonConverter : JsonConverter<Branch>
    {
        /// <summary>
        /// The format to use to serialize Timestamp
        /// </summary>
        public static string TimestampFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="Branch" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override Branch Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<Guid?> id = default;
            Option<Branch.TypeEnum?> type = default;
            Option<List<string>?> alias = default;
            Option<string?> created = default;
            Option<string?> deleted = default;
            Option<string?> description = default;
            Option<BranchHead?> head = default;
            Option<string?> name = default;
            Option<BranchOwningProject?> owningProject = default;
            Option<BranchHead?> referencedCommit = default;
            Option<DateTime?> timestamp = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "@id":
                            id = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        case "@type":
                            string? typeRawValue = utf8JsonReader.GetString();
                            if (typeRawValue != null)
                                type = new Option<Branch.TypeEnum?>(Branch.TypeEnumFromStringOrDefault(typeRawValue));
                            break;
                        case "alias":
                            alias = new Option<List<string>?>(JsonSerializer.Deserialize<List<string>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "created":
                            created = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "deleted":
                            deleted = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "description":
                            description = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "head":
                            head = new Option<BranchHead?>(JsonSerializer.Deserialize<BranchHead>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "owningProject":
                            owningProject = new Option<BranchOwningProject?>(JsonSerializer.Deserialize<BranchOwningProject>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "referencedCommit":
                            referencedCommit = new Option<BranchHead?>(JsonSerializer.Deserialize<BranchHead>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "timestamp":
                            timestamp = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            // Skip unknown properties
                            utf8JsonReader.Skip();
                            break;
                    }
                }
            }

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class Branch.");

            if (type.IsSet && type.Value == null)
                throw new ArgumentNullException(nameof(type), "Property is not nullable for class Branch.");

            // if (alias.IsSet && alias.Value == null)
            //     throw new ArgumentNullException(nameof(alias), "Property is not nullable for class Branch.");

            // if (created.IsSet && created.Value == null)
            //     throw new ArgumentNullException(nameof(created), "Property is not nullable for class Branch.");

            // if (deleted.IsSet && deleted.Value == null)
            //     throw new ArgumentNullException(nameof(deleted), "Property is not nullable for class Branch.");

            // if (description.IsSet && description.Value == null)
            //     throw new ArgumentNullException(nameof(description), "Property is not nullable for class Branch.");

            // if (head.IsSet && head.Value == null)
            //     throw new ArgumentNullException(nameof(head), "Property is not nullable for class Branch.");

            // if (name.IsSet && name.Value == null)
            //     throw new ArgumentNullException(nameof(name), "Property is not nullable for class Branch.");

            // if (owningProject.IsSet && owningProject.Value == null)
            //     throw new ArgumentNullException(nameof(owningProject), "Property is not nullable for class Branch.");

            // if (referencedCommit.IsSet && referencedCommit.Value == null)
            //     throw new ArgumentNullException(nameof(referencedCommit), "Property is not nullable for class Branch.");

            // if (timestamp.IsSet && timestamp.Value == null)
            //     throw new ArgumentNullException(nameof(timestamp), "Property is not nullable for class Branch.");

            return new Branch(id, type, alias, created, deleted, description, head, name, owningProject, referencedCommit, timestamp);
        }

        /// <summary>
        /// Serializes a <see cref="Branch" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="branch"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, Branch branch, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, branch, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="Branch" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="branch"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, Branch branch, JsonSerializerOptions jsonSerializerOptions)
        {
            if (branch.AliasOption.IsSet && branch.Alias == null)
                throw new ArgumentNullException(nameof(branch.Alias), "Property is required for class Branch.");

            if (branch.CreatedOption.IsSet && branch.Created == null)
                throw new ArgumentNullException(nameof(branch.Created), "Property is required for class Branch.");

            if (branch.DeletedOption.IsSet && branch.Deleted == null)
                throw new ArgumentNullException(nameof(branch.Deleted), "Property is required for class Branch.");

            if (branch.DescriptionOption.IsSet && branch.Description == null)
                throw new ArgumentNullException(nameof(branch.Description), "Property is required for class Branch.");

            if (branch.HeadOption.IsSet && branch.Head == null)
                throw new ArgumentNullException(nameof(branch.Head), "Property is required for class Branch.");

            if (branch.NameOption.IsSet && branch.Name == null)
                throw new ArgumentNullException(nameof(branch.Name), "Property is required for class Branch.");

            if (branch.OwningProjectOption.IsSet && branch.OwningProject == null)
                throw new ArgumentNullException(nameof(branch.OwningProject), "Property is required for class Branch.");

            if (branch.ReferencedCommitOption.IsSet && branch.ReferencedCommit == null)
                throw new ArgumentNullException(nameof(branch.ReferencedCommit), "Property is required for class Branch.");

            if (branch.IdOption.IsSet)
                writer.WriteString("@id", branch.IdOption.Value!.Value);

            var typeRawValue = Branch.TypeEnumToJsonValue(branch.TypeOption.Value!.Value);
            writer.WriteString("@type", typeRawValue);
            if (branch.AliasOption.IsSet)
            {
                writer.WritePropertyName("alias");
                JsonSerializer.Serialize(writer, branch.Alias, jsonSerializerOptions);
            }
            if (branch.CreatedOption.IsSet)
                writer.WriteString("created", branch.Created);

            if (branch.DeletedOption.IsSet)
                writer.WriteString("deleted", branch.Deleted);

            if (branch.DescriptionOption.IsSet)
                writer.WriteString("description", branch.Description);

            if (branch.HeadOption.IsSet)
            {
                writer.WritePropertyName("head");
                JsonSerializer.Serialize(writer, branch.Head, jsonSerializerOptions);
            }
            if (branch.NameOption.IsSet)
                writer.WriteString("name", branch.Name);

            if (branch.OwningProjectOption.IsSet)
            {
                writer.WritePropertyName("owningProject");
                JsonSerializer.Serialize(writer, branch.OwningProject, jsonSerializerOptions);
            }
            if (branch.ReferencedCommitOption.IsSet)
            {
                writer.WritePropertyName("referencedCommit");
                JsonSerializer.Serialize(writer, branch.ReferencedCommit, jsonSerializerOptions);
            }
            if (branch.TimestampOption.IsSet)
                writer.WriteString("timestamp", branch.TimestampOption.Value!.Value.ToString(TimestampFormat));
        }
    }
}
