// <auto-generated>
/*
 * SysML v2 API and Services
 *
 * REST/HTTP binding (PSM) for the SysML v2 standard API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Commit
    /// </summary>
    public partial class Commit : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Commit" /> class.
        /// </summary>
        /// <param name="id">id</param>
        /// <param name="type">type</param>
        /// <param name="change">change</param>
        /// <param name="owningProject">owningProject</param>
        /// <param name="previousCommit">previousCommit</param>
        [JsonConstructor]
        public Commit(Option<Guid?> id = default, Option<TypeEnum?> type = default, Option<List<DataVersion>?> change = default, Option<BranchOwningProject?> owningProject = default, Option<BranchHead?> previousCommit = default)
        {
            IdOption = id;
            TypeOption = type;
            ChangeOption = change;
            OwningProjectOption = owningProject;
            PreviousCommitOption = previousCommit;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Defines Type
        /// </summary>
        public enum TypeEnum
        {
            /// <summary>
            /// Enum Commit for value: Commit
            /// </summary>
            Commit = 1
        }

        /// <summary>
        /// Returns a <see cref="TypeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static TypeEnum TypeEnumFromString(string value)
        {
            if (value.Equals("Commit"))
                return TypeEnum.Commit;

            throw new NotImplementedException($"Could not convert value to type TypeEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="TypeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static TypeEnum? TypeEnumFromStringOrDefault(string value)
        {
            if (value.Equals("Commit"))
                return TypeEnum.Commit;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="TypeEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string TypeEnumToJsonValue(TypeEnum? value)
        {
            if (value == TypeEnum.Commit)
                return "Commit";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Used to track the state of Type
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<TypeEnum?> TypeOption { get; private set; }

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [JsonPropertyName("@type")]
        public TypeEnum? Type { get { return this.TypeOption; } set { this.TypeOption = new(value); } }

        /// <summary>
        /// Used to track the state of Id
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Guid?> IdOption { get; private set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("@id")]
        public Guid? Id { get { return this.IdOption; } set { this.IdOption = new(value); } }

        /// <summary>
        /// Used to track the state of Change
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<DataVersion>?> ChangeOption { get; private set; }

        /// <summary>
        /// Gets or Sets Change
        /// </summary>
        [JsonPropertyName("change")]
        public List<DataVersion>? Change { get { return this.ChangeOption; } set { this.ChangeOption = new(value); } }

        /// <summary>
        /// Used to track the state of OwningProject
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<BranchOwningProject?> OwningProjectOption { get; private set; }

        /// <summary>
        /// Gets or Sets OwningProject
        /// </summary>
        [JsonPropertyName("owningProject")]
        public BranchOwningProject? OwningProject { get { return this.OwningProjectOption; } set { this.OwningProjectOption = new(value); } }

        /// <summary>
        /// Used to track the state of PreviousCommit
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<BranchHead?> PreviousCommitOption { get; private set; }

        /// <summary>
        /// Gets or Sets PreviousCommit
        /// </summary>
        [JsonPropertyName("previousCommit")]
        public BranchHead? PreviousCommit { get { return this.PreviousCommitOption; } set { this.PreviousCommitOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Commit {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Change: ").Append(Change).Append("\n");
            sb.Append("  OwningProject: ").Append(OwningProject).Append("\n");
            sb.Append("  PreviousCommit: ").Append(PreviousCommit).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="Commit" />
    /// </summary>
    public class CommitJsonConverter : JsonConverter<Commit>
    {
        /// <summary>
        /// Deserializes json to <see cref="Commit" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override Commit Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<Guid?> id = default;
            Option<Commit.TypeEnum?> type = default;
            Option<List<DataVersion>?> change = default;
            Option<BranchOwningProject?> owningProject = default;
            Option<BranchHead?> previousCommit = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "@id":
                            id = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        case "@type":
                            string? typeRawValue = utf8JsonReader.GetString();
                            if (typeRawValue != null)
                                type = new Option<Commit.TypeEnum?>(Commit.TypeEnumFromStringOrDefault(typeRawValue));
                            break;
                        case "change":
                            change = new Option<List<DataVersion>?>(JsonSerializer.Deserialize<List<DataVersion>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "owningProject":
                            owningProject = new Option<BranchOwningProject?>(JsonSerializer.Deserialize<BranchOwningProject>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "previousCommit":
                            previousCommit = new Option<BranchHead?>(JsonSerializer.Deserialize<BranchHead>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class Commit.");

            if (type.IsSet && type.Value == null)
                throw new ArgumentNullException(nameof(type), "Property is not nullable for class Commit.");

            if (change.IsSet && change.Value == null)
                throw new ArgumentNullException(nameof(change), "Property is not nullable for class Commit.");

            if (owningProject.IsSet && owningProject.Value == null)
                throw new ArgumentNullException(nameof(owningProject), "Property is not nullable for class Commit.");

            if (previousCommit.IsSet && previousCommit.Value == null)
                throw new ArgumentNullException(nameof(previousCommit), "Property is not nullable for class Commit.");

            return new Commit(id, type, change, owningProject, previousCommit);
        }

        /// <summary>
        /// Serializes a <see cref="Commit" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="commit"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, Commit commit, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, commit, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="Commit" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="commit"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, Commit commit, JsonSerializerOptions jsonSerializerOptions)
        {
            if (commit.ChangeOption.IsSet && commit.Change == null)
                throw new ArgumentNullException(nameof(commit.Change), "Property is required for class Commit.");

            if (commit.OwningProjectOption.IsSet && commit.OwningProject == null)
                throw new ArgumentNullException(nameof(commit.OwningProject), "Property is required for class Commit.");

            if (commit.PreviousCommitOption.IsSet && commit.PreviousCommit == null)
                throw new ArgumentNullException(nameof(commit.PreviousCommit), "Property is required for class Commit.");

            if (commit.IdOption.IsSet)
                writer.WriteString("@id", commit.IdOption.Value!.Value);

            var typeRawValue = Commit.TypeEnumToJsonValue(commit.TypeOption.Value!.Value);
            writer.WriteString("@type", typeRawValue);
            if (commit.ChangeOption.IsSet)
            {
                writer.WritePropertyName("change");
                JsonSerializer.Serialize(writer, commit.Change, jsonSerializerOptions);
            }
            if (commit.OwningProjectOption.IsSet)
            {
                writer.WritePropertyName("owningProject");
                JsonSerializer.Serialize(writer, commit.OwningProject, jsonSerializerOptions);
            }
            if (commit.PreviousCommitOption.IsSet)
            {
                writer.WritePropertyName("previousCommit");
                JsonSerializer.Serialize(writer, commit.PreviousCommit, jsonSerializerOptions);
            }
        }
    }
}
