// <auto-generated>
/*
 * SysML v2 API and Services
 *
 * REST/HTTP binding (PSM) for the SysML v2 standard API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// CompositeConstraint
    /// </summary>
    public partial class CompositeConstraint : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CompositeConstraint" /> class.
        /// </summary>
        /// <param name="type">type</param>
        /// <param name="constraint">constraint</param>
        /// <param name="operator">operator</param>
        [JsonConstructor]
        public CompositeConstraint(Option<TypeEnum?> type = default, Option<List<Constraint>?> constraint = default, Option<OperatorEnum?> @operator = default)
        {
            TypeOption = type;
            ConstraintOption = constraint;
            OperatorOption = @operator;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Defines Type
        /// </summary>
        public enum TypeEnum
        {
            /// <summary>
            /// Enum CompositeConstraint for value: CompositeConstraint
            /// </summary>
            CompositeConstraint = 1
        }

        /// <summary>
        /// Returns a <see cref="TypeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static TypeEnum TypeEnumFromString(string value)
        {
            if (value.Equals("CompositeConstraint"))
                return TypeEnum.CompositeConstraint;

            throw new NotImplementedException($"Could not convert value to type TypeEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="TypeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static TypeEnum? TypeEnumFromStringOrDefault(string value)
        {
            if (value.Equals("CompositeConstraint"))
                return TypeEnum.CompositeConstraint;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="TypeEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string TypeEnumToJsonValue(TypeEnum? value)
        {
            if (value == TypeEnum.CompositeConstraint)
                return "CompositeConstraint";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Used to track the state of Type
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<TypeEnum?> TypeOption { get; private set; }

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [JsonPropertyName("@type")]
        public TypeEnum? Type { get { return this.TypeOption; } set { this.TypeOption = new(value); } }

        /// <summary>
        /// Defines Operator
        /// </summary>
        public enum OperatorEnum
        {
            /// <summary>
            /// Enum And for value: and
            /// </summary>
            And = 1,

            /// <summary>
            /// Enum Or for value: or
            /// </summary>
            Or = 2
        }

        /// <summary>
        /// Returns a <see cref="OperatorEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static OperatorEnum OperatorEnumFromString(string value)
        {
            if (value.Equals("and"))
                return OperatorEnum.And;

            if (value.Equals("or"))
                return OperatorEnum.Or;

            throw new NotImplementedException($"Could not convert value to type OperatorEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="OperatorEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static OperatorEnum? OperatorEnumFromStringOrDefault(string value)
        {
            if (value.Equals("and"))
                return OperatorEnum.And;

            if (value.Equals("or"))
                return OperatorEnum.Or;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="OperatorEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string OperatorEnumToJsonValue(OperatorEnum? value)
        {
            if (value == OperatorEnum.And)
                return "and";

            if (value == OperatorEnum.Or)
                return "or";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Used to track the state of Operator
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<OperatorEnum?> OperatorOption { get; private set; }

        /// <summary>
        /// Gets or Sets Operator
        /// </summary>
        [JsonPropertyName("operator")]
        public OperatorEnum? Operator { get { return this.OperatorOption; } set { this.OperatorOption = new(value); } }

        /// <summary>
        /// Used to track the state of Constraint
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<Constraint>?> ConstraintOption { get; private set; }

        /// <summary>
        /// Gets or Sets Constraint
        /// </summary>
        [JsonPropertyName("constraint")]
        public List<Constraint>? Constraint { get { return this.ConstraintOption; } set { this.ConstraintOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CompositeConstraint {\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Constraint: ").Append(Constraint).Append("\n");
            sb.Append("  Operator: ").Append(Operator).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="CompositeConstraint" />
    /// </summary>
    public class CompositeConstraintJsonConverter : JsonConverter<CompositeConstraint>
    {
        /// <summary>
        /// Deserializes json to <see cref="CompositeConstraint" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override CompositeConstraint Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<CompositeConstraint.TypeEnum?> type = default;
            Option<List<Constraint>?> constraint = default;
            Option<CompositeConstraint.OperatorEnum?> varOperator = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "@type":
                            string? typeRawValue = utf8JsonReader.GetString();
                            if (typeRawValue != null)
                                type = new Option<CompositeConstraint.TypeEnum?>(CompositeConstraint.TypeEnumFromStringOrDefault(typeRawValue));
                            break;
                        case "constraint":
                            constraint = new Option<List<Constraint>?>(JsonSerializer.Deserialize<List<Constraint>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "operator":
                            string? varOperatorRawValue = utf8JsonReader.GetString();
                            if (varOperatorRawValue != null)
                                varOperator = new Option<CompositeConstraint.OperatorEnum?>(CompositeConstraint.OperatorEnumFromStringOrDefault(varOperatorRawValue));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (type.IsSet && type.Value == null)
                throw new ArgumentNullException(nameof(type), "Property is not nullable for class CompositeConstraint.");

            if (constraint.IsSet && constraint.Value == null)
                throw new ArgumentNullException(nameof(constraint), "Property is not nullable for class CompositeConstraint.");

            if (varOperator.IsSet && varOperator.Value == null)
                throw new ArgumentNullException(nameof(varOperator), "Property is not nullable for class CompositeConstraint.");

            return new CompositeConstraint(type, constraint, varOperator);
        }

        /// <summary>
        /// Serializes a <see cref="CompositeConstraint" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="compositeConstraint"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, CompositeConstraint compositeConstraint, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, compositeConstraint, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="CompositeConstraint" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="compositeConstraint"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, CompositeConstraint compositeConstraint, JsonSerializerOptions jsonSerializerOptions)
        {
            if (compositeConstraint.ConstraintOption.IsSet && compositeConstraint.Constraint == null)
                throw new ArgumentNullException(nameof(compositeConstraint.Constraint), "Property is required for class CompositeConstraint.");

            var typeRawValue = CompositeConstraint.TypeEnumToJsonValue(compositeConstraint.TypeOption.Value!.Value);
            writer.WriteString("@type", typeRawValue);
            if (compositeConstraint.ConstraintOption.IsSet)
            {
                writer.WritePropertyName("constraint");
                JsonSerializer.Serialize(writer, compositeConstraint.Constraint, jsonSerializerOptions);
            }
            var varOperatorRawValue = CompositeConstraint.OperatorEnumToJsonValue(compositeConstraint.OperatorOption.Value!.Value);
            writer.WriteString("operator", varOperatorRawValue);
        }
    }
}
