// <auto-generated>
/*
 * SysML v2 API and Services
 *
 * REST/HTTP binding (PSM) for the SysML v2 standard API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// PrimitiveConstraint
    /// </summary>
    public partial class PrimitiveConstraint : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PrimitiveConstraint" /> class.
        /// </summary>
        /// <param name="type">type</param>
        /// <param name="inverse">inverse</param>
        /// <param name="property">property</param>
        /// <param name="value">value</param>
        /// <param name="operator">operator</param>
        [JsonConstructor]
        public PrimitiveConstraint(Option<TypeEnum?> type = default, Option<bool?> inverse = default, Option<string?> property = default, Option<string?> value = default, Option<OperatorEnum?> @operator = default)
        {
            TypeOption = type;
            InverseOption = inverse;
            PropertyOption = property;
            ValueOption = value;
            OperatorOption = @operator;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Defines Type
        /// </summary>
        public enum TypeEnum
        {
            /// <summary>
            /// Enum PrimitiveConstraint for value: PrimitiveConstraint
            /// </summary>
            PrimitiveConstraint = 1
        }

        /// <summary>
        /// Returns a <see cref="TypeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static TypeEnum TypeEnumFromString(string value)
        {
            if (value.Equals("PrimitiveConstraint"))
                return TypeEnum.PrimitiveConstraint;

            throw new NotImplementedException($"Could not convert value to type TypeEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="TypeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static TypeEnum? TypeEnumFromStringOrDefault(string value)
        {
            if (value.Equals("PrimitiveConstraint"))
                return TypeEnum.PrimitiveConstraint;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="TypeEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string TypeEnumToJsonValue(TypeEnum? value)
        {
            if (value == TypeEnum.PrimitiveConstraint)
                return "PrimitiveConstraint";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Used to track the state of Type
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<TypeEnum?> TypeOption { get; private set; }

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [JsonPropertyName("@type")]
        public TypeEnum? Type { get { return this.TypeOption; } set { this.TypeOption = new(value); } }

        /// <summary>
        /// Defines Operator
        /// </summary>
        public enum OperatorEnum
        {
            /// <summary>
            /// Enum Equal for value: &#x3D;
            /// </summary>
            Equal = 1,

            /// <summary>
            /// Enum GreaterThan for value: &gt;
            /// </summary>
            GreaterThan = 2,

            /// <summary>
            /// Enum LessThan for value: &lt;
            /// </summary>
            LessThan = 3
        }

        /// <summary>
        /// Returns a <see cref="OperatorEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static OperatorEnum OperatorEnumFromString(string value)
        {
            if (value.Equals("="))
                return OperatorEnum.Equal;

            if (value.Equals(">"))
                return OperatorEnum.GreaterThan;

            if (value.Equals("<"))
                return OperatorEnum.LessThan;

            throw new NotImplementedException($"Could not convert value to type OperatorEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="OperatorEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static OperatorEnum? OperatorEnumFromStringOrDefault(string value)
        {
            if (value.Equals("="))
                return OperatorEnum.Equal;

            if (value.Equals(">"))
                return OperatorEnum.GreaterThan;

            if (value.Equals("<"))
                return OperatorEnum.LessThan;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="OperatorEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string OperatorEnumToJsonValue(OperatorEnum? value)
        {
            if (value == OperatorEnum.Equal)
                return "=";

            if (value == OperatorEnum.GreaterThan)
                return ">";

            if (value == OperatorEnum.LessThan)
                return "<";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Used to track the state of Operator
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<OperatorEnum?> OperatorOption { get; private set; }

        /// <summary>
        /// Gets or Sets Operator
        /// </summary>
        [JsonPropertyName("operator")]
        public OperatorEnum? Operator { get { return this.OperatorOption; } set { this.OperatorOption = new(value); } }

        /// <summary>
        /// Used to track the state of Inverse
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> InverseOption { get; private set; }

        /// <summary>
        /// Gets or Sets Inverse
        /// </summary>
        [JsonPropertyName("inverse")]
        public bool? Inverse { get { return this.InverseOption; } set { this.InverseOption = new(value); } }

        /// <summary>
        /// Used to track the state of Property
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> PropertyOption { get; private set; }

        /// <summary>
        /// Gets or Sets Property
        /// </summary>
        [JsonPropertyName("property")]
        public string? Property { get { return this.PropertyOption; } set { this.PropertyOption = new(value); } }

        /// <summary>
        /// Used to track the state of Value
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ValueOption { get; private set; }

        /// <summary>
        /// Gets or Sets Value
        /// </summary>
        [JsonPropertyName("value")]
        public string? Value { get { return this.ValueOption; } set { this.ValueOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PrimitiveConstraint {\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Inverse: ").Append(Inverse).Append("\n");
            sb.Append("  Property: ").Append(Property).Append("\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("  Operator: ").Append(Operator).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="PrimitiveConstraint" />
    /// </summary>
    public class PrimitiveConstraintJsonConverter : JsonConverter<PrimitiveConstraint>
    {
        /// <summary>
        /// Deserializes json to <see cref="PrimitiveConstraint" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override PrimitiveConstraint Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<PrimitiveConstraint.TypeEnum?> type = default;
            Option<bool?> inverse = default;
            Option<string?> property = default;
            Option<string?> value = default;
            Option<PrimitiveConstraint.OperatorEnum?> varOperator = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "@type":
                            string? typeRawValue = utf8JsonReader.GetString();
                            if (typeRawValue != null)
                                type = new Option<PrimitiveConstraint.TypeEnum?>(PrimitiveConstraint.TypeEnumFromStringOrDefault(typeRawValue));
                            break;
                        case "inverse":
                            inverse = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "property":
                            property = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "value":
                            value = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "operator":
                            string? varOperatorRawValue = utf8JsonReader.GetString();
                            if (varOperatorRawValue != null)
                                varOperator = new Option<PrimitiveConstraint.OperatorEnum?>(PrimitiveConstraint.OperatorEnumFromStringOrDefault(varOperatorRawValue));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (type.IsSet && type.Value == null)
                throw new ArgumentNullException(nameof(type), "Property is not nullable for class PrimitiveConstraint.");

            if (inverse.IsSet && inverse.Value == null)
                throw new ArgumentNullException(nameof(inverse), "Property is not nullable for class PrimitiveConstraint.");

            if (property.IsSet && property.Value == null)
                throw new ArgumentNullException(nameof(property), "Property is not nullable for class PrimitiveConstraint.");

            if (value.IsSet && value.Value == null)
                throw new ArgumentNullException(nameof(value), "Property is not nullable for class PrimitiveConstraint.");

            if (varOperator.IsSet && varOperator.Value == null)
                throw new ArgumentNullException(nameof(varOperator), "Property is not nullable for class PrimitiveConstraint.");

            return new PrimitiveConstraint(type, inverse, property, value, varOperator);
        }

        /// <summary>
        /// Serializes a <see cref="PrimitiveConstraint" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="primitiveConstraint"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, PrimitiveConstraint primitiveConstraint, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, primitiveConstraint, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="PrimitiveConstraint" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="primitiveConstraint"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, PrimitiveConstraint primitiveConstraint, JsonSerializerOptions jsonSerializerOptions)
        {
            if (primitiveConstraint.PropertyOption.IsSet && primitiveConstraint.Property == null)
                throw new ArgumentNullException(nameof(primitiveConstraint.Property), "Property is required for class PrimitiveConstraint.");

            if (primitiveConstraint.ValueOption.IsSet && primitiveConstraint.Value == null)
                throw new ArgumentNullException(nameof(primitiveConstraint.Value), "Property is required for class PrimitiveConstraint.");

            var typeRawValue = PrimitiveConstraint.TypeEnumToJsonValue(primitiveConstraint.TypeOption.Value!.Value);
            writer.WriteString("@type", typeRawValue);
            if (primitiveConstraint.InverseOption.IsSet)
                writer.WriteBoolean("inverse", primitiveConstraint.InverseOption.Value!.Value);

            if (primitiveConstraint.PropertyOption.IsSet)
                writer.WriteString("property", primitiveConstraint.Property);

            if (primitiveConstraint.ValueOption.IsSet)
                writer.WriteString("value", primitiveConstraint.Value);

            var varOperatorRawValue = PrimitiveConstraint.OperatorEnumToJsonValue(primitiveConstraint.OperatorOption.Value!.Value);
            writer.WriteString("operator", varOperatorRawValue);
        }
    }
}
