// <auto-generated>
/*
 * SysML v2 API and Services
 *
 * REST/HTTP binding (PSM) for the SysML v2 standard API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Query
    /// </summary>
    public partial class Query : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Query" /> class.
        /// </summary>
        /// <param name="id">id</param>
        /// <param name="type">type</param>
        /// <param name="owningProject">owningProject</param>
        /// <param name="scope">scope</param>
        /// <param name="select">select</param>
        /// <param name="where">where</param>
        [JsonConstructor]
        public Query(Option<Guid?> id = default, Option<TypeEnum?> type = default, Option<BranchOwningProject?> owningProject = default, Option<List<DataIdentity>?> scope = default, Option<List<string>?> select = default, Option<Constraint?> where = default)
        {
            IdOption = id;
            TypeOption = type;
            OwningProjectOption = owningProject;
            ScopeOption = scope;
            SelectOption = select;
            WhereOption = where;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Defines Type
        /// </summary>
        public enum TypeEnum
        {
            /// <summary>
            /// Enum Query for value: Query
            /// </summary>
            Query = 1
        }

        /// <summary>
        /// Returns a <see cref="TypeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static TypeEnum TypeEnumFromString(string value)
        {
            if (value.Equals("Query"))
                return TypeEnum.Query;

            throw new NotImplementedException($"Could not convert value to type TypeEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="TypeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static TypeEnum? TypeEnumFromStringOrDefault(string value)
        {
            if (value.Equals("Query"))
                return TypeEnum.Query;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="TypeEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string TypeEnumToJsonValue(TypeEnum? value)
        {
            if (value == TypeEnum.Query)
                return "Query";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Used to track the state of Type
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<TypeEnum?> TypeOption { get; private set; }

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [JsonPropertyName("@type")]
        public TypeEnum? Type { get { return this.TypeOption; } set { this.TypeOption = new(value); } }

        /// <summary>
        /// Used to track the state of Id
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Guid?> IdOption { get; private set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("@id")]
        public Guid? Id { get { return this.IdOption; } set { this.IdOption = new(value); } }

        /// <summary>
        /// Used to track the state of OwningProject
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<BranchOwningProject?> OwningProjectOption { get; private set; }

        /// <summary>
        /// Gets or Sets OwningProject
        /// </summary>
        [JsonPropertyName("owningProject")]
        public BranchOwningProject? OwningProject { get { return this.OwningProjectOption; } set { this.OwningProjectOption = new(value); } }

        /// <summary>
        /// Used to track the state of Scope
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<DataIdentity>?> ScopeOption { get; private set; }

        /// <summary>
        /// Gets or Sets Scope
        /// </summary>
        [JsonPropertyName("scope")]
        public List<DataIdentity>? Scope { get { return this.ScopeOption; } set { this.ScopeOption = new(value); } }

        /// <summary>
        /// Used to track the state of Select
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<string>?> SelectOption { get; private set; }

        /// <summary>
        /// Gets or Sets Select
        /// </summary>
        [JsonPropertyName("select")]
        public List<string>? Select { get { return this.SelectOption; } set { this.SelectOption = new(value); } }

        /// <summary>
        /// Used to track the state of Where
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Constraint?> WhereOption { get; private set; }

        /// <summary>
        /// Gets or Sets Where
        /// </summary>
        [JsonPropertyName("where")]
        public Constraint? Where { get { return this.WhereOption; } set { this.WhereOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Query {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  OwningProject: ").Append(OwningProject).Append("\n");
            sb.Append("  Scope: ").Append(Scope).Append("\n");
            sb.Append("  Select: ").Append(Select).Append("\n");
            sb.Append("  Where: ").Append(Where).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="Query" />
    /// </summary>
    public class QueryJsonConverter : JsonConverter<Query>
    {
        /// <summary>
        /// Deserializes json to <see cref="Query" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override Query Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<Guid?> id = default;
            Option<Query.TypeEnum?> type = default;
            Option<BranchOwningProject?> owningProject = default;
            Option<List<DataIdentity>?> scope = default;
            Option<List<string>?> select = default;
            Option<Constraint?> where = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "@id":
                            id = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        case "@type":
                            string? typeRawValue = utf8JsonReader.GetString();
                            if (typeRawValue != null)
                                type = new Option<Query.TypeEnum?>(Query.TypeEnumFromStringOrDefault(typeRawValue));
                            break;
                        case "owningProject":
                            owningProject = new Option<BranchOwningProject?>(JsonSerializer.Deserialize<BranchOwningProject>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "scope":
                            scope = new Option<List<DataIdentity>?>(JsonSerializer.Deserialize<List<DataIdentity>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "select":
                            select = new Option<List<string>?>(JsonSerializer.Deserialize<List<string>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "where":
                            where = new Option<Constraint?>(JsonSerializer.Deserialize<Constraint>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class Query.");

            if (type.IsSet && type.Value == null)
                throw new ArgumentNullException(nameof(type), "Property is not nullable for class Query.");

            if (owningProject.IsSet && owningProject.Value == null)
                throw new ArgumentNullException(nameof(owningProject), "Property is not nullable for class Query.");

            if (scope.IsSet && scope.Value == null)
                throw new ArgumentNullException(nameof(scope), "Property is not nullable for class Query.");

            if (select.IsSet && select.Value == null)
                throw new ArgumentNullException(nameof(select), "Property is not nullable for class Query.");

            if (where.IsSet && where.Value == null)
                throw new ArgumentNullException(nameof(where), "Property is not nullable for class Query.");

            return new Query(id, type, owningProject, scope, select, where);
        }

        /// <summary>
        /// Serializes a <see cref="Query" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="query"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, Query query, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, query, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="Query" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="query"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, Query query, JsonSerializerOptions jsonSerializerOptions)
        {
            if (query.OwningProjectOption.IsSet && query.OwningProject == null)
                throw new ArgumentNullException(nameof(query.OwningProject), "Property is required for class Query.");

            if (query.ScopeOption.IsSet && query.Scope == null)
                throw new ArgumentNullException(nameof(query.Scope), "Property is required for class Query.");

            if (query.SelectOption.IsSet && query.Select == null)
                throw new ArgumentNullException(nameof(query.Select), "Property is required for class Query.");

            if (query.WhereOption.IsSet && query.Where == null)
                throw new ArgumentNullException(nameof(query.Where), "Property is required for class Query.");

            if (query.IdOption.IsSet)
                writer.WriteString("@id", query.IdOption.Value!.Value);

            var typeRawValue = Query.TypeEnumToJsonValue(query.TypeOption.Value!.Value);
            writer.WriteString("@type", typeRawValue);
            if (query.OwningProjectOption.IsSet)
            {
                writer.WritePropertyName("owningProject");
                JsonSerializer.Serialize(writer, query.OwningProject, jsonSerializerOptions);
            }
            if (query.ScopeOption.IsSet)
            {
                writer.WritePropertyName("scope");
                JsonSerializer.Serialize(writer, query.Scope, jsonSerializerOptions);
            }
            if (query.SelectOption.IsSet)
            {
                writer.WritePropertyName("select");
                JsonSerializer.Serialize(writer, query.Select, jsonSerializerOptions);
            }
            if (query.WhereOption.IsSet)
            {
                writer.WritePropertyName("where");
                JsonSerializer.Serialize(writer, query.Where, jsonSerializerOptions);
            }
        }
    }
}
