// <auto-generated>
/*
 * SysML v2 API and Services
 *
 * REST/HTTP binding (PSM) for the SysML v2 standard API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Relationship
    /// </summary>
    public partial class Relationship : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Relationship" /> class.
        /// </summary>
        /// <param name="id">id</param>
        /// <param name="type">type</param>
        /// <param name="identifier">identifier</param>
        /// <param name="source">source</param>
        /// <param name="target">target</param>
        [JsonConstructor]
        public Relationship(Option<Guid?> id = default, Option<string?> type = default, Option<Guid?> identifier = default, Option<List<Identified>?> source = default, Option<List<Identified>?> target = default)
        {
            IdOption = id;
            TypeOption = type;
            IdentifierOption = identifier;
            SourceOption = source;
            TargetOption = target;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Id
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Guid?> IdOption { get; private set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("@id")]
        public Guid? Id { get { return this.IdOption; } set { this.IdOption = new(value); } }

        /// <summary>
        /// Used to track the state of Type
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> TypeOption { get; private set; }

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [JsonPropertyName("@type")]
        public string? Type { get { return this.TypeOption; } set { this.TypeOption = new(value); } }

        /// <summary>
        /// Used to track the state of Identifier
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Guid?> IdentifierOption { get; private set; }

        /// <summary>
        /// Gets or Sets Identifier
        /// </summary>
        [JsonPropertyName("identifier")]
        public Guid? Identifier { get { return this.IdentifierOption; } set { this.IdentifierOption = new(value); } }

        /// <summary>
        /// Used to track the state of Source
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<Identified>?> SourceOption { get; private set; }

        /// <summary>
        /// Gets or Sets Source
        /// </summary>
        [JsonPropertyName("source")]
        public List<Identified>? Source { get { return this.SourceOption; } set { this.SourceOption = new(value); } }

        /// <summary>
        /// Used to track the state of Target
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<Identified>?> TargetOption { get; private set; }

        /// <summary>
        /// Gets or Sets Target
        /// </summary>
        [JsonPropertyName("target")]
        public List<Identified>? Target { get { return this.TargetOption; } set { this.TargetOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Relationship {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Identifier: ").Append(Identifier).Append("\n");
            sb.Append("  Source: ").Append(Source).Append("\n");
            sb.Append("  Target: ").Append(Target).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="Relationship" />
    /// </summary>
    public class RelationshipJsonConverter : JsonConverter<Relationship>
    {
        /// <summary>
        /// Deserializes json to <see cref="Relationship" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override Relationship Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<Guid?> id = default;
            Option<string?> type = default;
            Option<Guid?> identifier = default;
            Option<List<Identified>?> source = default;
            Option<List<Identified>?> target = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "@id":
                            id = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        case "@type":
                            type = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "identifier":
                            identifier = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        case "source":
                            source = new Option<List<Identified>?>(JsonSerializer.Deserialize<List<Identified>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "target":
                            target = new Option<List<Identified>?>(JsonSerializer.Deserialize<List<Identified>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class Relationship.");

            if (type.IsSet && type.Value == null)
                throw new ArgumentNullException(nameof(type), "Property is not nullable for class Relationship.");

            if (identifier.IsSet && identifier.Value == null)
                throw new ArgumentNullException(nameof(identifier), "Property is not nullable for class Relationship.");

            if (source.IsSet && source.Value == null)
                throw new ArgumentNullException(nameof(source), "Property is not nullable for class Relationship.");

            if (target.IsSet && target.Value == null)
                throw new ArgumentNullException(nameof(target), "Property is not nullable for class Relationship.");

            return new Relationship(id, type, identifier, source, target);
        }

        /// <summary>
        /// Serializes a <see cref="Relationship" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="relationship"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, Relationship relationship, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, relationship, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="Relationship" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="relationship"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, Relationship relationship, JsonSerializerOptions jsonSerializerOptions)
        {
            if (relationship.TypeOption.IsSet && relationship.Type == null)
                throw new ArgumentNullException(nameof(relationship.Type), "Property is required for class Relationship.");

            if (relationship.SourceOption.IsSet && relationship.Source == null)
                throw new ArgumentNullException(nameof(relationship.Source), "Property is required for class Relationship.");

            if (relationship.TargetOption.IsSet && relationship.Target == null)
                throw new ArgumentNullException(nameof(relationship.Target), "Property is required for class Relationship.");

            if (relationship.IdOption.IsSet)
                writer.WriteString("@id", relationship.IdOption.Value!.Value);

            if (relationship.TypeOption.IsSet)
                writer.WriteString("@type", relationship.Type);

            if (relationship.IdentifierOption.IsSet)
                writer.WriteString("identifier", relationship.IdentifierOption.Value!.Value);

            if (relationship.SourceOption.IsSet)
            {
                writer.WritePropertyName("source");
                JsonSerializer.Serialize(writer, relationship.Source, jsonSerializerOptions);
            }
            if (relationship.TargetOption.IsSet)
            {
                writer.WritePropertyName("target");
                JsonSerializer.Serialize(writer, relationship.Target, jsonSerializerOptions);
            }
        }
    }
}
