// <auto-generated>
/*
 * SysML v2 API and Services
 *
 * REST/HTTP binding (PSM) for the SysML v2 standard API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Tag
    /// </summary>
    public partial class Tag : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Tag" /> class.
        /// </summary>
        /// <param name="id">id</param>
        /// <param name="type">type</param>
        /// <param name="name">name</param>
        /// <param name="owningProject">owningProject</param>
        /// <param name="referencedCommit">referencedCommit</param>
        /// <param name="taggedCommit">taggedCommit</param>
        /// <param name="timestamp">timestamp</param>
        [JsonConstructor]
        public Tag(Option<Guid?> id = default, Option<TypeEnum?> type = default, Option<string?> name = default, Option<BranchOwningProject?> owningProject = default, Option<BranchHead?> referencedCommit = default, Option<BranchHead?> taggedCommit = default, Option<DateTime?> timestamp = default)
        {
            IdOption = id;
            TypeOption = type;
            NameOption = name;
            OwningProjectOption = owningProject;
            ReferencedCommitOption = referencedCommit;
            TaggedCommitOption = taggedCommit;
            TimestampOption = timestamp;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Defines Type
        /// </summary>
        public enum TypeEnum
        {
            /// <summary>
            /// Enum Tag for value: Tag
            /// </summary>
            Tag = 1
        }

        /// <summary>
        /// Returns a <see cref="TypeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static TypeEnum TypeEnumFromString(string value)
        {
            if (value.Equals("Tag"))
                return TypeEnum.Tag;

            throw new NotImplementedException($"Could not convert value to type TypeEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="TypeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static TypeEnum? TypeEnumFromStringOrDefault(string value)
        {
            if (value.Equals("Tag"))
                return TypeEnum.Tag;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="TypeEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string TypeEnumToJsonValue(TypeEnum? value)
        {
            if (value == TypeEnum.Tag)
                return "Tag";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Used to track the state of Type
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<TypeEnum?> TypeOption { get; private set; }

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [JsonPropertyName("@type")]
        public TypeEnum? Type { get { return this.TypeOption; } set { this.TypeOption = new(value); } }

        /// <summary>
        /// Used to track the state of Id
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Guid?> IdOption { get; private set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("@id")]
        public Guid? Id { get { return this.IdOption; } set { this.IdOption = new(value); } }

        /// <summary>
        /// Used to track the state of Name
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> NameOption { get; private set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [JsonPropertyName("name")]
        public string? Name { get { return this.NameOption; } set { this.NameOption = new(value); } }

        /// <summary>
        /// Used to track the state of OwningProject
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<BranchOwningProject?> OwningProjectOption { get; private set; }

        /// <summary>
        /// Gets or Sets OwningProject
        /// </summary>
        [JsonPropertyName("owningProject")]
        public BranchOwningProject? OwningProject { get { return this.OwningProjectOption; } set { this.OwningProjectOption = new(value); } }

        /// <summary>
        /// Used to track the state of ReferencedCommit
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<BranchHead?> ReferencedCommitOption { get; private set; }

        /// <summary>
        /// Gets or Sets ReferencedCommit
        /// </summary>
        [JsonPropertyName("referencedCommit")]
        public BranchHead? ReferencedCommit { get { return this.ReferencedCommitOption; } set { this.ReferencedCommitOption = new(value); } }

        /// <summary>
        /// Used to track the state of TaggedCommit
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<BranchHead?> TaggedCommitOption { get; private set; }

        /// <summary>
        /// Gets or Sets TaggedCommit
        /// </summary>
        [JsonPropertyName("taggedCommit")]
        public BranchHead? TaggedCommit { get { return this.TaggedCommitOption; } set { this.TaggedCommitOption = new(value); } }

        /// <summary>
        /// Used to track the state of Timestamp
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTime?> TimestampOption { get; private set; }

        /// <summary>
        /// Gets or Sets Timestamp
        /// </summary>
        [JsonPropertyName("timestamp")]
        public DateTime? Timestamp { get { return this.TimestampOption; } set { this.TimestampOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Tag {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  OwningProject: ").Append(OwningProject).Append("\n");
            sb.Append("  ReferencedCommit: ").Append(ReferencedCommit).Append("\n");
            sb.Append("  TaggedCommit: ").Append(TaggedCommit).Append("\n");
            sb.Append("  Timestamp: ").Append(Timestamp).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="Tag" />
    /// </summary>
    public class TagJsonConverter : JsonConverter<Tag>
    {
        /// <summary>
        /// The format to use to serialize Timestamp
        /// </summary>
        public static string TimestampFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="Tag" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override Tag Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<Guid?> id = default;
            Option<Tag.TypeEnum?> type = default;
            Option<string?> name = default;
            Option<BranchOwningProject?> owningProject = default;
            Option<BranchHead?> referencedCommit = default;
            Option<BranchHead?> taggedCommit = default;
            Option<DateTime?> timestamp = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "@id":
                            id = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        case "@type":
                            string? typeRawValue = utf8JsonReader.GetString();
                            if (typeRawValue != null)
                                type = new Option<Tag.TypeEnum?>(Tag.TypeEnumFromStringOrDefault(typeRawValue));
                            break;
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "owningProject":
                            owningProject = new Option<BranchOwningProject?>(JsonSerializer.Deserialize<BranchOwningProject>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "referencedCommit":
                            referencedCommit = new Option<BranchHead?>(JsonSerializer.Deserialize<BranchHead>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "taggedCommit":
                            taggedCommit = new Option<BranchHead?>(JsonSerializer.Deserialize<BranchHead>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "timestamp":
                            timestamp = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class Tag.");

            if (type.IsSet && type.Value == null)
                throw new ArgumentNullException(nameof(type), "Property is not nullable for class Tag.");

            if (name.IsSet && name.Value == null)
                throw new ArgumentNullException(nameof(name), "Property is not nullable for class Tag.");

            if (owningProject.IsSet && owningProject.Value == null)
                throw new ArgumentNullException(nameof(owningProject), "Property is not nullable for class Tag.");

            if (referencedCommit.IsSet && referencedCommit.Value == null)
                throw new ArgumentNullException(nameof(referencedCommit), "Property is not nullable for class Tag.");

            if (taggedCommit.IsSet && taggedCommit.Value == null)
                throw new ArgumentNullException(nameof(taggedCommit), "Property is not nullable for class Tag.");

            if (timestamp.IsSet && timestamp.Value == null)
                throw new ArgumentNullException(nameof(timestamp), "Property is not nullable for class Tag.");

            return new Tag(id, type, name, owningProject, referencedCommit, taggedCommit, timestamp);
        }

        /// <summary>
        /// Serializes a <see cref="Tag" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="tag"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, Tag tag, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, tag, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="Tag" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="tag"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, Tag tag, JsonSerializerOptions jsonSerializerOptions)
        {
            if (tag.NameOption.IsSet && tag.Name == null)
                throw new ArgumentNullException(nameof(tag.Name), "Property is required for class Tag.");

            if (tag.OwningProjectOption.IsSet && tag.OwningProject == null)
                throw new ArgumentNullException(nameof(tag.OwningProject), "Property is required for class Tag.");

            if (tag.ReferencedCommitOption.IsSet && tag.ReferencedCommit == null)
                throw new ArgumentNullException(nameof(tag.ReferencedCommit), "Property is required for class Tag.");

            if (tag.TaggedCommitOption.IsSet && tag.TaggedCommit == null)
                throw new ArgumentNullException(nameof(tag.TaggedCommit), "Property is required for class Tag.");

            if (tag.IdOption.IsSet)
                writer.WriteString("@id", tag.IdOption.Value!.Value);

            var typeRawValue = Tag.TypeEnumToJsonValue(tag.TypeOption.Value!.Value);
            writer.WriteString("@type", typeRawValue);
            if (tag.NameOption.IsSet)
                writer.WriteString("name", tag.Name);

            if (tag.OwningProjectOption.IsSet)
            {
                writer.WritePropertyName("owningProject");
                JsonSerializer.Serialize(writer, tag.OwningProject, jsonSerializerOptions);
            }
            if (tag.ReferencedCommitOption.IsSet)
            {
                writer.WritePropertyName("referencedCommit");
                JsonSerializer.Serialize(writer, tag.ReferencedCommit, jsonSerializerOptions);
            }
            if (tag.TaggedCommitOption.IsSet)
            {
                writer.WritePropertyName("taggedCommit");
                JsonSerializer.Serialize(writer, tag.TaggedCommit, jsonSerializerOptions);
            }
            if (tag.TimestampOption.IsSet)
                writer.WriteString("timestamp", tag.TimestampOption.Value!.Value.ToString(TimestampFormat));
        }
    }
}
